# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WOC



  target 'WOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WOC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WOC-tvOS

  target 'WOC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
