BUTTON_CHANGE_PASSWORD: "Change Password"
BUTTON_CONTINUE: "Continue"
BUTTON_UPDATE: "Update"
CENTER_ADDRESS: "Address"
CENTER_ADDRESS1: "Address 1"
CENTER_CITY: "City"
CENTER_CODE: "Center code"
CENTER_CODE_ERROR: "Please enter Center code"
CENTER_CONTACT_PERSON: "Contact person"
CENTER_DETAILS: "Center details"
CENTER_DETAILS_ERROR: "Please enter Center details"
CENTER_DISTRICT: "District"
CENTER_EMAIL: "Email"
CENTER_HINT: "Search by Keyword"
CENTER_NAME: "Centre Name"
CENTER_OTHER_DETAILS: "Other Details"
CENTER_PHONE_NO: "Phone No"
CENTER_PIN_CODE: "Pin Code"
CENTER_SELECT: "Select state"
CENTER_SELECT_CITY: "Select City"
CENTER_STATE: "State"
CHOOSE_LANGUAGE: "Choose Language"
CONFIRM_PASSWORD: "Confirm Password"
CONTACT_DETAILS: "Contact details"
CONTACT_DETAILS_ERROR: "Please enter Contact details"
COURSE_DETAILS: "Course details"
COURSE_DETAILS_ERROR: "Please enter Course details"
COURSE_TITLE: "Course Title"
COURSE_TITLE_ERROR: "Please enter course title"
EARNING_MEMBER: "Earning Member's Name"
EARNING_MEMBER_ERROR: "Please enter Earning member"
END_DATE: "Select completion Date"
ERROR_NETWORK: "Please check your Internet Connection"
FAMILY_INCOME: "Family Income"
FAMILY_INCOME_ERROR: "Please enter Family Income"
FEEDBACK_MESSAGE: "Message"
FEEDBACK_MESSAGE_ERROR: "Please enter message"
FEEDBACK_TYPE: "Select Type"
FEEDBACK_TYPE_ERROR: "Please select type"
FORGORT_PASSWORD_VALID_ERROR: "Please enter Valid Password"
FORGOT_BUTTON_CANCEL: "Cancel"
FORGOT_BUTTON_OK: "OK"
FORGOT_EMAIL: "Email"
FORGOT_EMAIL_ERROR: "Please enter email"
FORGOT_HEADER: "Forgot Password"
JOB_DATE: "Job/Business Date"
LANGUAGE_ERROR: "Please Select Language"
LOADING_HEADER: "Please wait "
LOGIN_BUTTON_SIGN_IN: "Sign In"
LOGIN_BUTTON_SIGN_UP: "Sign Up"
LOGIN_EMAIL_ERROR: "Please enter Email"
LOGIN_EMAIL_HINT: "Email"
LOGIN_EMAIL_VALID_ERROR: "Please enter valid Email"
LOGIN_FORGOT_PASSWORD: "Forgot Password?"
LOGIN_HEADER: "Login"
LOGIN_PASSWORD_ERROR: "Please enter Password"
LOGIN_PASSWORD_HINT: "Password"
LOGOUT_TITLE: "Are you sure you want to Logout?"
MENU_ABOUT_US: "About Us"
MENU_DONATE: "Donate"
MENU_FEEDBACK: "Feedback Form"
MENU_HOME: "Home"
MENU_JOB: "Training/Job Status"
MENU_LANGUAGE: "Language"
MENU_LOGOUT: "Logout"
MENU_PROFILE: "Profile"
MENU_SCHOLARSHIP: "Scholarship Form"
MENU_SUGGESSTION: "Suggested Centres"
MENU_TRAINING: "Training Centres"
NEW_PASSWORD: "New Password"
NEW_PASSWORD_ERROR: "Please enter New Password"
NO_DATA: "No Data Found"
OLD_PASSWORD: "Old password"
OLD_PASSWORD_ERROR: "Please enter old password"
PASSWORD_MISMATCH: "Password mismatch"
PATIENT_RELATION: "Relationship with Patient"
PATIENT_RELATION_ERROR: "Please enter Patient  Relation"
REGISTER_AGE: "Age"
REGISTER_AGE_ERROR: "Please enter age"
REGISTER_BUTTON_SIN_IN: "Sign In"
REGISTER_BUTTON_SUBMIT: "Submit"
REGISTER_CITY: "City"
REGISTER_CITY_ERROR: "Please enter City"
REGISTER_CONFIRM_PASSWORD: "Confirm password"
REGISTER_CONFIRM_PASSWORD_ERROR: "Please confirm Password"
REGISTER_CONTACT_INFO: "Contact Information"
REGISTER_EMAIL: "E-mail"
REGISTER_EMAIL_ERROR: "Please enter Email"
REGISTER_EMAIL_VALID_ERROR: "Please enter Valid Email"
REGISTER_EXPERIENCE: "Experience"
REGISTER_EXPERIENCE_ERROR: "Please enter Experience"
REGISTER_GENDER: "Select Gender"
REGISTER_GENDER_ERROR: "Please select Gender"
REGISTER_HEADER: "Sign Up"
REGISTER_HEADER_PATIENT: "Patient Information"
REGISTER_LAST_NAME: "Last Name"
REGISTER_LAST_NAME_ERROR: "Please enter  Last Name"
REGISTER_MISMATCH_ERROR: "Password mismatch"
REGISTER_MOBILE_NO: "Mobile"
REGISTER_MOBILE_NO_ERROR: "Please enter Mobile No"
REGISTER_NAME: "First Name"
REGISTER_NAME_ERROR: "Please enter Name"
REGISTER_OLD_ACCOUNT: "Already have an account?"
REGISTER_PASSWORD: "Password"
REGISTER_PASSWORD_ERROR: "Please enter Password"
REGISTER_PATIENT_ADDRESS: "Patient Address"
REGISTER_PATIENT_ADDRESS_ERROR: "Please enter patient Address"
REGISTER_PATIENT_DETAILS: "Details about Patient's Illness"
REGISTER_PATIENT_DETAILS_ERROR: "Please enter patient details"
REGISTER_PATIENT_NAME: "Patient Name"
REGISTER_PATIENT_NAME_ERROR: "Please enter patient Name"
REGISTER_PATIENT_NO: "Patient Contact Number"
REGISTER_PATIENT_NO_ERROR: "Please enter patient Contact Number"
REGISTER_PATIENT_RELATION: "Relationship with Patient"
REGISTER_PATIENT_RELATION_ERROR: "Please enter patient Relation"
REGISTER_PERSONAL_INFO: "Personal Information"
REGISTER_PINCODE: "Pin Code"
REGISTER_PINCODE_ERROR: "Please enter Pincode"
REGISTER_QUALIFICATION_ERROR: "Please enter Qualification"
REGISTER_Qualification: "Qualification"
REGISTER_STATE: "State"
REGISTER_STATE_ERROR: "Please enter State"
SCHOLARSHIP_DETAILS: "Scholarship Details"
SCHOLARSHIP_DETAILS_ERROR: "Please enter Scholarship Details"
SCHOLARSHIP_TYPE: "Select Type"
SCHOLARSHIP_TYPE_ERROR: "Please Select Type"
SELECT_FEEDBACK_CENTERS: "Centers"
SELECT_FEEDBACK_COURSES: "Courses"
SELECT_FEEDBACK_JOBS: "Jobs"
SELECT_FEEDBACK_OTHER: "Other"
SELECT_FEEDBACK_SCHOLARSHIP: "Scholarship"
SELECT_FEEDBACK_SELECT: "Select Feedback"
SELECT_GENDER_FEMALE: "Female"
SELECT_GENDER_MALE: "Male"
SELECT_GENDER_OTHERS: "Others"
SELECT_GENDER_SELECT: "Select Gender"
SELECT_JOB_NOT_TAKEN: "Not Taken"
SELECT_JOB_SELECT: "Select Job Status"
SELECT_JOB_TAKEN: "Taken"
SELECT_SCHOLARSHIP_COST: "Cost"
SELECT_SCHOLARSHIP_OTHER: "Other"
SELECT_SCHOLARSHIP_SELECT: "Select Scholarship"
START_DATE: "Select Start Date"
TRAINING_COST: "Training cost"
TRAINING_COST_ERROR: "Please enter Training cost"
TRAINING_COURSE: "Course engaged"
TRAINING_COURSE_ERROR: "Please enter Course"
TRAINING_DURATION: "Training duration"
TRAINING_DURATION_ERROR: "Please enter Training duration"
TRAINING_END_DATE: "Training Completion Date"
TRAINING_END_DATE_ERROR: "Please enter Completed date"
TRAINING_JOB: "Job/Business Start Date"
TRAINING_JOB_ERROR: "Please enter job/business started date"
TRAINING_JOB_TITLE: "Job/ Business Title"
TRAINING_JOB_TITLE_ERROR: "Please enter Job/ Business Title"
TRAINING_NAME: "Training Centre"
TRAINING_NAME_ERROR: "Please enter training center name"
TRAINING_SALARY: "Salary"
TRAINING_SALARY_ERROR: "Please enter Salary"
TRAINING_SCHOLARSHIP: "Select scholarship"
TRAINING_SCHOLARSHIP_ERROR: "Please Select scholarship"
TRAINING_START_DATE: "Training Start Date"
TRAINING_START_DATE_ERROR: "Please enter start date"
__proto__: Object

1. Add functionality to display home screen heading in different language
2. Check API functionality to search suggested centre keyword.