<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

</body>
</html>


{
    "response": {
        "message": "Languages",
        "body": {
            "en": {
                "LOGIN_HEADER": "Login",
                "LOGIN_EMAIL_HINT": "Email",
                "LOGIN_PASSWORD_HINT": "Password",
                "LOGIN_BUTTON_SIGN_IN": "Sign In",
                "LOGIN_BUTTON_SIGN_UP": "Sign Up",
                "LOGIN_FORGOT_PASSWORD": "Forgot Password?",
                "LOGIN_EMAIL_ERROR": "Please enter Email",
                "LOGIN_PASSWORD_ERROR": "Please enter Password",
                "REGISTER_HEADER": "Sign Up",
                "REGISTER_HEADER_PATIENT": "Patient Information",
                "REGISTER_PATIENT_NAME": "Patient Name",
                "REGISTER_PATIENT_NO": "Patient Contact Number",
                "REGISTER_PATIENT_RELATION": "Relationship with Patient",
                "REGISTER_PATIENT_ADDRESS": "Patient Address",
                "REGISTER_PATIENT_DETAILS": "Details about Patient's Illness",
                "REGISTER_PERSONAL_INFO": "Personal Information",
                "REGISTER_NAME": "First Name",
                "REGISTER_LAST_NAME": "Last Name",
                "REGISTER_AGE": "Age",
                "REGISTER_GENDER": "Select Gender",
                "REGISTER_Qualification": "Qualification",
                "REGISTER_EXPERIENCE": "Experience",
                "REGISTER_CONTACT_INFO": "Contact Information",
                "REGISTER_MOBILE_NO": "Mobile",
                "REGISTER_EMAIL": "E-mail",
                "REGISTER_PASSWORD": "Password",
                "REGISTER_CONFIRM_PASSWORD": "Confirm password",
                "REGISTER_STATE": "State",
                "REGISTER_CITY": "City",
                "REGISTER_PINCODE": "Pin Code",
                "REGISTER_OLD_ACCOUNT": "Already have an account?",
                "REGISTER_BUTTON_SIN_IN": "Sign In",
                "REGISTER_PATIENT_NAME_ERROR": "Please enter patient Name",
                "REGISTER_PATIENT_NO_ERROR": "Please enter patient Contact Number",
                "REGISTER_PATIENT_RELATION_ERROR": "Please enter patient Relation",
                "REGISTER_PATIENT_ADDRESS_ERROR": "Please enter patient Address",
                "REGISTER_PATIENT_DETAILS_ERROR": "Please enter patient details",
                "REGISTER_NAME_ERROR": "Please enter Name",
                "REGISTER_LAST_NAME_ERROR": "Please enter  Last Name",
                "REGISTER_AGE_ERROR": "Please enter age",
                "REGISTER_GENDER_ERROR": "Please select Gender",
                "REGISTER_QUALIFICATION_ERROR": "Please enter Qualification",
                "REGISTER_EXPERIENCE_ERROR": "Please enter Experience",
                "REGISTER_MOBILE_NO_ERROR": "Please enter Mobile No",
                "REGISTER_EMAIL_ERROR": "Please enter Email",
                "REGISTER_PASSWORD_ERROR": "Please enter Password",
                "REGISTER_CONFIRM_PASSWORD_ERROR": "Please confirm Password",
                "REGISTER_MISMATCH_ERROR": "Password mismatch",
                "REGISTER_STATE_ERROR": "Please enter State",
                "REGISTER_CITY_ERROR": "Please enter City",
                "REGISTER_PINCODE_ERROR": "Please enter Pincode",
                "FORGOT_HEADER": "Forgot Password",
                "FORGOT_EMAIL": "Email",
                "FORGOT_EMAIL_ERROR": "Please enter email",
                "FORGOT_BUTTON_OK": "OK",
                "FORGOT_BUTTON_CANCEL": "Cancel",
                "OLD_PASSWORD": "Old password",
                "NEW_PASSWORD": "New Password",
                "CONFIRM_PASSWORD": "Confirm Password",
                "OLD_PASSWORD_ERROR": "Please enter old password",
                "NEW_PASSWORD_ERROR": "Please enter New Password",
                "CHOOSE_LANGUAGE": "Choose Language",
                "BUTTON_CONTINUE": "Continue",
                "LANGUAGE_ERROR": "Please Select Language",
                "BUTTON_UPDATE": "Update",
                "BUTTON_CHANGE_PASSWORD": "Change Password",
                "LOADING_HEADER": "Please wait ",
                "LOGOUT_TITLE": "Are you sure you want to Logout?",
                "CENTER_CONTACT_PERSON": "Contact person",
                "CENTER_NAME": "Centre Name",
                "CENTER_STATE": "State",
                "CENTER_DISTRICT": "District",
                "CENTER_CITY": "City",
                "CENTER_ADDRESS": "Address",
                "CENTER_ADDRESS1": "Address 1",
                "CENTER_PHONE_NO": "Phone No",
                "CENTER_EMAIL": "Email",
                "CENTER_OTHER_DETAILS": "Other Details",
                "CENTER_HINT": "Search by Keyword",
                "CENTER_SELECT": "Select state",
                "MENU_HOME": "Home",
                "MENU_TRAINING": "Training Centres",
                "MENU_PROFILE": "Profile",
                "MENU_DONATE": "Donate",
                "MENU_ABOUT_US": "About Us",
                "MENU_SCHOLARSHIP": "Scholarship Form",
                "MENU_LANGUAGE": "Language",
                "MENU_LOGOUT": "Logout",
                "MENU_SUGGESSTION": "Suggested Centres",
                "MENU_JOB": "Training/Job Status",
                "MENU_FEEDBACK": "Feedback Form",
                "TRAINING_NAME": "Training Centre",
                "TRAINING_NAME_ERROR": "Please enter training center name",
                "TRAINING_COURSE": "Course engaged",
                "TRAINING_COURSE_ERROR": "Please enter Course",
                "TRAINING_SCHOLARSHIP": "Select scholarship",
                "TRAINING_SCHOLARSHIP_ERROR": "Please Select scholarship",
                "TRAINING_START_DATE": "Training Start Date",
                "TRAINING_START_DATE_ERROR": "Please enter start date",
                "TRAINING_END_DATE": "Training Completion Date",
                "TRAINING_END_DATE_ERROR": "Please enter Completed date",
                "TRAINING_JOB": "Job/Business Start Date",
                "TRAINING_JOB_ERROR": "Please enter job/business started date",
                "TRAINING_JOB_TITLE": "Job/ Business Title",
                "TRAINING_JOB_TITLE_ERROR": "Please enter Job/ Business Title",
                "TRAINING_SALARY": "Salary",
                "TRAINING_SALARY_ERROR": "Please enter Salary",
                "FEEDBACK_TYPE": "Select Type",
                "FEEDBACK_MESSAGE": "Message",
                "FEEDBACK_TYPE_ERROR": "Please select type",
                "FEEDBACK_MESSAGE_ERROR": "Please enter message",
                "FAMILY_INCOME": "Family Income",
                "FAMILY_INCOME_ERROR": "Please enter Family Income",
                "EARNING_MEMBER": "Earning Member's Name",
                "EARNING_MEMBER_ERROR": "Please enter Earning member",
                "PATIENT_RELATION": "Relationship with Patient",
                "PATIENT_RELATION_ERROR": "Please enter Patient  Relation",
                "CENTER_CODE": "Center code",
                "CENTER_CODE_ERROR": "Please enter Center code",
                "CENTER_DETAILS": "Center details",
                "CENTER_DETAILS_ERROR": "Please enter Center details",
                "COURSE_TITLE": "Course Title",
                "COURSE_TITLE_ERROR": "Please enter course title",
                "COURSE_DETAILS": "Course details",
                "COURSE_DETAILS_ERROR": "Please enter Course details",
                "TRAINING_DURATION": "Training duration",
                "TRAINING_DURATION_ERROR": "Please enter Training duration",
                "TRAINING_COST": "Training cost",
                "TRAINING_COST_ERROR": "Please enter Training cost",
                "SCHOLARSHIP_TYPE": "Select Type",
                "SCHOLARSHIP_TYPE_ERROR": "Please Select Type",
                "SCHOLARSHIP_DETAILS": "Scholarship Details",
                "SCHOLARSHIP_DETAILS_ERROR": "Please enter Scholarship Details",
                "CONTACT_DETAILS": "Contact details",
                "CONTACT_DETAILS_ERROR": "Please enter Contact details",
                "LOGIN_EMAIL_VALID_ERROR": "Please enter valid Email",
                "REGISTER_EMAIL_VALID_ERROR": "Please enter Valid Email",
                "FORGORT_PASSWORD_VALID_ERROR": "Please enter Valid Password",
                "PASSWORD_MISMATCH": "Password mismatch",
                "CENTER_PIN_CODE": "Pin Code",
                "NO_DATA": "No Data Found",
                "START_DATE": "Select Start Date",
                "END_DATE": "Select completion Date",
                "JOB_DATE": "Job/Business Date",
                "ERROR_NETWORK": "Please check your Internet Connection",
                "SELECT_GENDER_SELECT": "Select Gender",
                "SELECT_GENDER_MALE": "Male",
                "SELECT_GENDER_FEMALE": "Female",
                "SELECT_GENDER_OTHERS": "Others",
                "SELECT_SCHOLARSHIP_SELECT": "Select Scholarship",
                "SELECT_SCHOLARSHIP_COST": "Cost",
                "SELECT_SCHOLARSHIP_OTHER": "Other",
                "SELECT_JOB_SELECT": "Select Job Status",
                "SELECT_JOB_TAKEN": "Taken",
                "SELECT_JOB_NOT_TAKEN": "Not Taken",
                "SELECT_FEEDBACK_SELECT": "Select Feedback",
                "SELECT_FEEDBACK_CENTERS": "Centers",
                "SELECT_FEEDBACK_COURSES": "Courses",
                "SELECT_FEEDBACK_SCHOLARSHIP": "Scholarship",
                "SELECT_FEEDBACK_JOBS": "Jobs",
                "SELECT_FEEDBACK_OTHER": "Other",
                "CENTER_SELECT_CITY": "Select City",
                "REGISTER_BUTTON_SUBMIT": "Submit",
                "MENU_IT_PARTNER": "IT Partner"
            },
            "ta": {
                "LOGIN_HEADER": "உள் நுழை",
                "LOGIN_EMAIL_HINT": "மின்னஞ்சல்",
                "LOGIN_PASSWORD_HINT": "கடவுச்சொல்",
                "LOGIN_BUTTON_SIGN_IN": "உள்நுழைக",
                "LOGIN_BUTTON_SIGN_UP": "இணைந்ததற்கு",
                "LOGIN_FORGOT_PASSWORD": "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
                "LOGIN_EMAIL_ERROR": "தயவுசெய்து மின்னஞ்சல் உள்ளிடவும்",
                "LOGIN_PASSWORD_ERROR": "கடவுச்சொல்லை உள்ளிடவும்",
                "REGISTER_HEADER": "பதிவு பெறுதல் படிவம்",
                "REGISTER_HEADER_PATIENT": "நோயாளி தகவல்",
                "REGISTER_PATIENT_NAME": "நோயாளி பெயர்",
                "REGISTER_PATIENT_NO": "நோயாளியின் தொடர்பு எண்",
                "REGISTER_PATIENT_RELATION": "நோயாளி உறவு",
                "REGISTER_PATIENT_ADDRESS": "நோயாளியின் முகவரி",
                "REGISTER_PATIENT_DETAILS": "நோயாளியின் நோய்",
                "REGISTER_PERSONAL_INFO": "தனிப்பட்ட தகவல்",
                "REGISTER_NAME": "முதல் பெயர்",
                "REGISTER_LAST_NAME": "கடைசி பெயர்",
                "REGISTER_AGE": "வயது",
                "REGISTER_GENDER": "பாலினம்",
                "REGISTER_Qualification": "தகுதி",
                "REGISTER_EXPERIENCE": "அனுபவம்",
                "REGISTER_CONTACT_INFO": "தொடர்பு தகவல்",
                "REGISTER_MOBILE_NO": "மொபைல் எண்",
                "REGISTER_EMAIL": "மின்னஞ்சல் முகவரி",
                "REGISTER_PASSWORD": "கடவுச்சொல்",
                "REGISTER_CONFIRM_PASSWORD": "கடவுச்சொல்லை உறுதிப்படுத்துக",
                "REGISTER_STATE": "நிலை",
                "REGISTER_CITY": "நகரம்",
                "REGISTER_PINCODE": "அஞ்சல் குறியீடு",
                "REGISTER_OLD_ACCOUNT": "ஏற்கனவே ஒரு கணக்கு உள்ளதா",
                "REGISTER_BUTTON_SIN_IN": "உள்நுழைக",
                "REGISTER_PATIENT_NAME_ERROR": "தயவுசெய்து நோயாளியின் பெயரை உள்ளிடுக",
                "REGISTER_PATIENT_NO_ERROR": "தயவுசெய்து நோயாளியின் எண்ணை உள்ளிடுக",
                "REGISTER_PATIENT_RELATION_ERROR": "தயவுசெய்து நோயாளி உறவு உள்ளிடவும்",
                "REGISTER_PATIENT_ADDRESS_ERROR": "முகவரியை உள்ளிடவும்",
                "REGISTER_PATIENT_DETAILS_ERROR": "தயவுசெய்து நோயாளியின் நோய்க்கு உள்ளிடவும்",
                "REGISTER_NAME_ERROR": "முதல் பெயரை உள்ளிடவும்",
                "REGISTER_LAST_NAME_ERROR": "கடைசி பெயரை உள்ளிடவும்",
                "REGISTER_AGE_ERROR": "வயதில் நுழையுங்கள்",
                "REGISTER_GENDER_ERROR": "தயவுசெய்து பாலினத்தை உள்ளிடவும்",
                "REGISTER_QUALIFICATION_ERROR": "தகுதி உள்ளிடவும்",
                "REGISTER_EXPERIENCE_ERROR": "அனுபவம் உள்ளிடுக",
                "REGISTER_MOBILE_NO_ERROR": "தயவுசெய்து மொபைல் எண் உள்ளிடவும்",
                "REGISTER_EMAIL_ERROR": "தயவுசெய்து மின்னஞ்சல் உள்ளிடவும்",
                "REGISTER_PASSWORD_ERROR": "கடவுச்சொல்லை உள்ளிடவும்",
                "REGISTER_CONFIRM_PASSWORD_ERROR": "கடவுச்சொல்லை உறுதிப்படுத்துக",
                "REGISTER_MISMATCH_ERROR": "கடவுச்சொல் பொருந்தாது",
                "REGISTER_STATE_ERROR": "தயவுசெய்து நிலை உள்ளிடுக",
                "REGISTER_CITY_ERROR": "தயவுசெய்து நகருக்குள் நுழையுங்கள்",
                "REGISTER_PINCODE_ERROR": "தயவுசெய்து பின்செல் உள்ளிடவும்",
                "FORGOT_HEADER": "கடவுச்சொல்லை மறந்துவிட்டீர்களா",
                "FORGOT_EMAIL": "மின்னஞ்சல்",
                "FORGOT_EMAIL_ERROR": "தயவுசெய்து மின்னஞ்சல் உள்ளிடவும்",
                "FORGOT_BUTTON_OK": "சரி",
                "FORGOT_BUTTON_CANCEL": "ரத்து",
                "OLD_PASSWORD": "பழைய கடவுச்சொல்",
                "NEW_PASSWORD": "புதிய கடவுச்சொல்",
                "CONFIRM_PASSWORD": "கடவுச்சொல் சரிபார்க்கவும்",
                "OLD_PASSWORD_ERROR": "பழைய கடவுச்சொல்லை உள்ளிடவும்",
                "NEW_PASSWORD_ERROR": "புதிய கடவுச்சொல்லை உள்ளிடவும்",
                "CHOOSE_LANGUAGE": "மொழியைத் தேர்ந்தெடு",
                "BUTTON_CONTINUE": "தொடர்ந்து",
                "LANGUAGE_ERROR": "மொழியைத் தேர்ந்தெடு",
                "BUTTON_UPDATE": "மேம்படுத்தல்",
                "BUTTON_CHANGE_PASSWORD": "கடவுச்சொல்லை மாற்று",
                "LOADING_HEADER": "தயவுசெய்து காத்திருங்கள்",
                "LOGOUT_TITLE": "நீங்கள் வெளியேற வேண்டுமா?",
                "CENTER_CONTACT_PERSON": "தொடர்பு நபரை",
                "CENTER_NAME": "சென்டர் பெயர்",
                "CENTER_STATE": "நிலை",
                "CENTER_DISTRICT": "மாவட்டம்",
                "CENTER_CITY": "நகரம்",
                "CENTER_ADDRESS": "முகவரி",
                "CENTER_ADDRESS1": "முகவரி-1",
                "CENTER_PHONE_NO": "தொலைபேசி எண்",
                "CENTER_EMAIL": "மின்னஞ்சல்",
                "CENTER_OTHER_DETAILS": "வேறு தகவல்கள்",
                "CENTER_HINT": "முக்கிய மூலம் தேட",
                "CENTER_SELECT": "மாநில தேர்வு",
                "MENU_HOME": "வீட்டில்",
                "MENU_TRAINING": "பயிற்சி",
                "MENU_PROFILE": "சுயவிவர",
                "MENU_DONATE": "தானம்",
                "MENU_ABOUT_US": "எங்களை பற்றி",
                "MENU_SCHOLARSHIP": "உதவித்தொகை",
                "MENU_LANGUAGE": "மொழி",
                "MENU_LOGOUT": "வெளியேறு",
                "MENU_SUGGESSTION": "பரிந்துரை மையங்கள்",
                "MENU_JOB": "பயிற்சி / வேலை நிலை",
                "MENU_FEEDBACK": "கருத்து வடிவம்",
                "TRAINING_NAME": "பயிற்சி மையம்",
                "TRAINING_NAME_ERROR": "பயிற்சி மையத்தில் நுழையுங்கள்",
                "TRAINING_COURSE": "நிச்சயமாக ஈடுபட்டுள்ளது",
                "TRAINING_COURSE_ERROR": "தயவுசெய்து நிச்சயமாக ஈடுபடுக",
                "TRAINING_SCHOLARSHIP": "ஸ்காலர்ஷிப்பைத் தேர்ந்தெடுக்கவும்",
                "TRAINING_SCHOLARSHIP_ERROR": "ஸ்காலர்ஷிப் தேர்ந்தெடுக்கவும்",
                "TRAINING_START_DATE": "தொடக்க தேதி",
                "TRAINING_START_DATE_ERROR": "தொடக்க தேதி உள்ளிடுக",
                "TRAINING_END_DATE": "கடைசி தேதி",
                "TRAINING_END_DATE_ERROR": "முடிவு தேதி உள்ளிடவும்",
                "TRAINING_JOB": "வேலை தேதியின் தேதி",
                "TRAINING_JOB_ERROR": "வேலை ஆரம்ப தேதி உள்ளிடவும்",
                "TRAINING_JOB_TITLE": "வேலை / வணிக தலைப்பு",
                "TRAINING_JOB_TITLE_ERROR": "வேலை / வணிக தலைப்பு உள்ளிடவும்",
                "TRAINING_SALARY": "சம்பளம்",
                "TRAINING_SALARY_ERROR": "சம்பளத்தில் நுழையுங்கள்",
                "FEEDBACK_TYPE": "வகை தேர்வு",
                "FEEDBACK_MESSAGE": "செய்தி",
                "FEEDBACK_TYPE_ERROR": "தயவுசெய்து வகை தேர்ந்தெடுக்கவும்",
                "FEEDBACK_MESSAGE_ERROR": "செய்தியை உள்ளிடவும்",
                "FAMILY_INCOME": "குடும்ப சம்பளம்",
                "FAMILY_INCOME_ERROR": "குடும்ப சம்பளத்தில் நுழையுங்கள்",
                "EARNING_MEMBER": "ஊதிய உறுப்பினர்",
                "EARNING_MEMBER_ERROR": "ஊதிய உறுப்பினர்",
                "PATIENT_RELATION": "நோயாளிக்கு உறவு",
                "PATIENT_RELATION_ERROR": "நோயாளிக்கு உறவு உள்ளிடுக",
                "CENTER_CODE": "சென்டர் குறியீடு",
                "CENTER_CODE_ERROR": "மைய குறியீட்டை உள்ளிடவும்",
                "CENTER_DETAILS": "சென்டர் விவரங்கள்",
                "CENTER_DETAILS_ERROR": "சென்டர் விவரங்களை உள்ளிடவும்",
                "COURSE_TITLE": "பாடத்தின் தலைப்பு",
                "COURSE_TITLE_ERROR": "நிச்சயமாக தலைப்பு உள்ளிடவும்",
                "COURSE_DETAILS": "நிச்சயமாக விவரங்கள்",
                "COURSE_DETAILS_ERROR": "நிச்சயமாக விவரங்கள் உள்ளிடவும்",
                "TRAINING_DURATION": "நிச்சயமாக கால",
                "TRAINING_DURATION_ERROR": "நிச்சயமாக காலவரை உள்ளிடவும்",
                "TRAINING_COST": "பயிற்சி செலவு",
                "TRAINING_COST_ERROR": "பயிற்சி செலவில் நுழையுங்கள்",
                "SCHOLARSHIP_TYPE": "வகை தேர்வு",
                "SCHOLARSHIP_TYPE_ERROR": "தயவுசெய்து வகை தேர்ந்தெடுக்கவும்",
                "SCHOLARSHIP_DETAILS": "ஸ்காலர்ஷிப் விவரங்கள்",
                "SCHOLARSHIP_DETAILS_ERROR": "ஸ்காலர்ஷிப் விவரங்கள்",
                "CONTACT_DETAILS": "தொடர்பு விபரங்கள்",
                "CONTACT_DETAILS_ERROR": "தொடர்பு விவரங்களை உள்ளிடவும்",
                "LOGIN_EMAIL_VALID_ERROR": "LOGIN_EMAIL_VALID_ERROR",
                "REGISTER_EMAIL_VALID_ERROR": "REGISTER_EMAIL_VALID_ERROR",
                "FORGORT_PASSWORD_VALID_ERROR": "FORGORT_PASSWORD_VALID_ERROR",
                "PASSWORD_MISMATCH": "PASSWORD_MISMATCH",
                "CENTER_PIN_CODE": "CENTER_PIN_CODE",
                "NO_DATA": "NO_DATA",
                "START_DATE": "START_DATE",
                "END_DATE": "END_DATE",
                "JOB_DATE": "JOB_DATE",
                "ERROR_NETWORK": "ERROR_NETWORK",
                "SELECT_GENDER_SELECT": "SELECT_GENDER_SELECT",
                "SELECT_GENDER_MALE": "SELECT_GENDER_MALE",
                "SELECT_GENDER_FEMALE": "SELECT_GENDER_FEMALE",
                "SELECT_GENDER_OTHERS": "SELECT_GENDER_OTHERS",
                "SELECT_SCHOLARSHIP_SELECT": "SELECT_SCHOLARSHIP_SELECT",
                "SELECT_SCHOLARSHIP_COST": "SELECT_SCHOLARSHIP_COST",
                "SELECT_SCHOLARSHIP_OTHER": "SELECT_SCHOLARSHIP_OTHER",
                "SELECT_JOB_SELECT": "SELECT_JOB_SELECT",
                "SELECT_JOB_TAKEN": "SELECT_JOB_TAKEN",
                "SELECT_JOB_NOT_TAKEN": "SELECT_JOB_NOT_TAKEN",
                "SELECT_FEEDBACK_SELECT": "SELECT_FEEDBACK_SELECT",
                "SELECT_FEEDBACK_CENTERS": "SELECT_FEEDBACK_CENTERS",
                "SELECT_FEEDBACK_COURSES": "SELECT_FEEDBACK_COURSES",
                "SELECT_FEEDBACK_SCHOLARSHIP": "SELECT_FEEDBACK_SCHOLARSHIP",
                "SELECT_FEEDBACK_JOBS": "SELECT_FEEDBACK_JOBS",
                "SELECT_FEEDBACK_OTHER": "SELECT_FEEDBACK_OTHER",
                "CENTER_SELECT_CITY": "CENTER_SELECT_CITY",
                "REGISTER_BUTTON_SUBMIT": "REGISTER_BUTTON_SUBMIT"
            },
            "hi": {
                "LOGIN_HEADER": "लॉगिन",
                "LOGIN_EMAIL_HINT": "ईमेल",
                "LOGIN_PASSWORD_HINT": "पासवर्ड",
                "LOGIN_BUTTON_SIGN_IN": "साइन इन करें",
                "LOGIN_BUTTON_SIGN_UP": "साइन अप करें",
                "LOGIN_FORGOT_PASSWORD": "पासवर्ड भूल गए?",
                "LOGIN_EMAIL_ERROR": "ईमेल दर्ज करें",
                "LOGIN_PASSWORD_ERROR": "पास वर्ड दर्ज करें",
                "REGISTER_HEADER": "साइनअप फॉर्म",
                "REGISTER_HEADER_PATIENT": "मरीज़ की जानकारी",
                "REGISTER_PATIENT_NAME": "मरीज़ का नाम",
                "REGISTER_PATIENT_NO": "मरीज़ का फोन नंबर",
                "REGISTER_PATIENT_RELATION": "मरीज़ के साथ संबंध",
                "REGISTER_PATIENT_ADDRESS": "मरीज़ का पता",
                "REGISTER_PATIENT_DETAILS": "मरीज़ की समस्या",
                "REGISTER_PERSONAL_INFO": "व्यक्तिगत जानकारी",
                "REGISTER_NAME": "मूल नाम",
                "REGISTER_LAST_NAME": "अंतिम नाम",
                "REGISTER_AGE": "आयु",
                "REGISTER_GENDER": "लिंग चुनें",
                "REGISTER_Qualification": "योग्यता",
                "REGISTER_EXPERIENCE": "अनुभव",
                "REGISTER_CONTACT_INFO": "संपर्क जानकारी",
                "REGISTER_MOBILE_NO": "मोबाइल",
                "REGISTER_EMAIL": "ईमेल",
                "REGISTER_PASSWORD": "पासवर्ड",
                "REGISTER_CONFIRM_PASSWORD": "पासवर्ड की पुष्टि कीजिये",
                "REGISTER_STATE": "राज्य",
                "REGISTER_CITY": "शहर",
                "REGISTER_PINCODE": "पिन कोड",
                "REGISTER_OLD_ACCOUNT": "क्या आपके पास पहले से एक खाता मौजूद है",
                "REGISTER_BUTTON_SIN_IN": "साइन इन करें",
                "REGISTER_PATIENT_NAME_ERROR": "मरीज़ का नाम दीजिए",
                "REGISTER_PATIENT_NO_ERROR": "मरीज़ का नंबर डीजिये",
                "REGISTER_PATIENT_RELATION_ERROR": "कृपया रोगी से संबंध दर्ज करें",
                "REGISTER_PATIENT_ADDRESS_ERROR": "कृपया रोगी का पता दर्ज करें",
                "REGISTER_PATIENT_DETAILS_ERROR": "कृपया रोगी की समस्या दर्ज करें",
                "REGISTER_NAME_ERROR": "कृपया पहला नाम दर्ज करें",
                "REGISTER_LAST_NAME_ERROR": "कृपया अंतिम नाम दर्ज करें",
                "REGISTER_AGE_ERROR": "कृपया उम्र दर्ज करें",
                "REGISTER_GENDER_ERROR": "कृपया लिंग दर्ज करें",
                "REGISTER_QUALIFICATION_ERROR": "कृपया योग्यता दर्ज करें",
                "REGISTER_EXPERIENCE_ERROR": "कृपया अनुभव दर्ज करें",
                "REGISTER_MOBILE_NO_ERROR": "कृपया मोबाइल नंबर दर्ज करें",
                "REGISTER_EMAIL_ERROR": "कृपया ईमेल दर्ज करें",
                "REGISTER_PASSWORD_ERROR": "कृप्या पास्वर्ड भरो",
                "REGISTER_CONFIRM_PASSWORD_ERROR": "कृपया पासवर्ड की पुष्टि करें",
                "REGISTER_MISMATCH_ERROR": "पासवर्ड का मेल नहीं हुआ",
                "REGISTER_STATE_ERROR": "कृपया राज्य दर्ज करें",
                "REGISTER_CITY_ERROR": "कृपया शहर दर्ज करें",
                "REGISTER_PINCODE_ERROR": "कृपया पिनकोड दर्ज करें",
                "FORGOT_HEADER": "पासवर्ड भूल गए",
                "FORGOT_EMAIL": "ईमेल",
                "FORGOT_EMAIL_ERROR": "कृपया ईमेल दर्ज करें",
                "FORGOT_BUTTON_OK": "आगे बढ़ें",
                "FORGOT_BUTTON_CANCEL": "रद्द करें",
                "OLD_PASSWORD": "पुराना पासवर्ड",
                "NEW_PASSWORD": "नया पासवर्ड",
                "CONFIRM_PASSWORD": "पासवर्ड की पुष्टि कीजिये",
                "OLD_PASSWORD_ERROR": "कृपया पुराना पासवर्ड दर्ज करें",
                "NEW_PASSWORD_ERROR": "कृपया नया पासवर्ड दर्ज करें",
                "CHOOSE_LANGUAGE": "भाषा चुनें",
                "BUTTON_CONTINUE": "आगे बढ़ें",
                "LANGUAGE_ERROR": "कृपया भाषा का चुनाव करें",
                "BUTTON_UPDATE": "अपडेट",
                "BUTTON_CHANGE_PASSWORD": "पासवर्ड बदलें",
                "LOADING_HEADER": "कृपया प्रतीक्षा करें",
                "LOGOUT_TITLE": "क्या आप लॉग आउट करना चाहते हैं?",
                "CENTER_CONTACT_PERSON": "व्यक्ति का नाम",
                "CENTER_NAME": "केंद्र का नाम",
                "CENTER_STATE": "राज्य",
                "CENTER_DISTRICT": "जिला",
                "CENTER_CITY": "शहर",
                "CENTER_ADDRESS": "पता",
                "CENTER_ADDRESS1": "पता-1",
                "CENTER_PHONE_NO": "फ़ोन नंबर",
                "CENTER_EMAIL": "ईमेल",
                "CENTER_OTHER_DETAILS": "अन्य जानकारी",
                "CENTER_HINT": "कीवर्ड द्वारा खोज",
                "CENTER_SELECT": "राज्य चुनें",
                "MENU_HOME": "होम",
                "MENU_TRAINING": "ट्रेनिंग",
                "MENU_PROFILE": "प्रोफ़ाइल",
                "MENU_DONATE": "कृपया दान दें",
                "MENU_ABOUT_US": "हमारे बारे में",
                "MENU_SCHOLARSHIP": "छात्रवृत्ति",
                "MENU_LANGUAGE": "भाषा",
                "MENU_LOGOUT": "लोग आउट",
                "MENU_SUGGESSTION": "सुझाए गए केंद्र",
                "MENU_JOB": "ट्रेनिंग/ नौकरी फार्म",
                "MENU_FEEDBACK": "प्रतिक्रिया फॉर्म",
                "TRAINING_NAME": "ट्रेनिंग केंद्र",
                "TRAINING_NAME_ERROR": "कृपया ट्रेनिंग केंद्र दर्ज करें",
                "TRAINING_COURSE": "चुना हुआ ट्रेनिंग कोर्स",
                "TRAINING_COURSE_ERROR": "कृपया चुना हुआ ट्रेनिंग कोर्स दर्ज करें",
                "TRAINING_SCHOLARSHIP": "छात्रवृत्ति का चयन करें",
                "TRAINING_SCHOLARSHIP_ERROR": "कृपया छात्रवृत्ति का चयन करें",
                "TRAINING_START_DATE": "आरंभ करने की तिथि",
                "TRAINING_START_DATE_ERROR": "कृपया प्रारंभ तिथि दर्ज करें",
                "TRAINING_END_DATE": "पूरा होने की तारीख",
                "TRAINING_END_DATE_ERROR": "पूरा होने की तारीख दर्ज करें",
                "TRAINING_JOB": "नौकरी की आरंभ तिथि",
                "TRAINING_JOB_ERROR": "कृपया नौकरी की आरंभ तिथि दर्ज करें",
                "TRAINING_JOB_TITLE": "नौकरी / व्यापार शीर्षक",
                "TRAINING_JOB_TITLE_ERROR": "कृपया नौकरी / व्यापार शीर्षक दर्ज करें",
                "TRAINING_SALARY": "वेतन",
                "TRAINING_SALARY_ERROR": "कृपया वेतन दर्ज करें",
                "FEEDBACK_TYPE": "प्रकार चुनें",
                "FEEDBACK_MESSAGE": "संदेश",
                "FEEDBACK_TYPE_ERROR": "कृपया प्रकार का चयन करें",
                "FEEDBACK_MESSAGE_ERROR": "कृपया संदेश दर्ज करें",
                "FAMILY_INCOME": "पारिवारिक आय",
                "FAMILY_INCOME_ERROR": "कृपया पारिवारिक आय दर्ज करें",
                "EARNING_MEMBER": "कमाई सदस्य का नाम",
                "EARNING_MEMBER_ERROR": "कृपया कमाई सदस्य का नाम दर्ज करें",
                "PATIENT_RELATION": "रोगी के साथ संबंध",
                "PATIENT_RELATION_ERROR": "कृपया रोगी के साथ संबंध दर्ज करें",
                "CENTER_CODE": "केंद्र कोड दर्ज करें",
                "CENTER_CODE_ERROR": "कृपया केंद्र कोड दर्ज करें",
                "CENTER_DETAILS": "केंद्र की जानकारी",
                "CENTER_DETAILS_ERROR": "कृपया केंद्र की जानकारी दर्ज करें",
                "COURSE_TITLE": "पाठ्यक्रम का विषय",
                "COURSE_TITLE_ERROR": "कृपया पाठ्यक्रम का शीर्षक दर्ज करें",
                "COURSE_DETAILS": "पाठ्यक्रम की जानकारी",
                "COURSE_DETAILS_ERROR": "कृपया पाठ्यक्रम की जानकारी दर्ज करें",
                "TRAINING_DURATION": "ट्रेनिंग की अवधि",
                "TRAINING_DURATION_ERROR": "ट्रेनिंग की अवधि दर्ज करें",
                "TRAINING_COST": "ट्रेनिंग की लागत",
                "TRAINING_COST_ERROR": "ट्रेनिंग की लागत दर्ज करें",
                "SCHOLARSHIP_TYPE": "प्रकार चुनें",
                "SCHOLARSHIP_TYPE_ERROR": "कृपया प्रकार का चयन करें",
                "SCHOLARSHIP_DETAILS": "छात्रवृत्ति की जानकारी",
                "SCHOLARSHIP_DETAILS_ERROR": "छात्रवृत्ति की जानकारी दर्ज करें",
                "CONTACT_DETAILS": "संपर्क की जानकारी",
                "CONTACT_DETAILS_ERROR": "संपर्क की जानकारी दर्ज करें",
                "LOGIN_EMAIL_VALID_ERROR": "लॉगिन ईमेल थीक नाहिन है",
                "REGISTER_EMAIL_VALID_ERROR": "साइनअप ईमेल थीक नाहिन है",
                "FORGORT_PASSWORD_VALID_ERROR": "पासवर्ड का मेल नहीं हुआ",
                "PASSWORD_MISMATCH": "पासवर्ड का मेल नहीं हुआ",
                "CENTER_PIN_CODE": "केंद्र का पिनकोड",
                "NO_DATA": "कोई डेटा उपलब्ध नहीं है",
                "START_DATE": "शुरुआत की तारीख",
                "END_DATE": "अंत की तारीख",
                "JOB_DATE": "नौकरी पाने की तारीख",
                "ERROR_NETWORK": "कोई नेटवर्क नहीं है",
                "SELECT_GENDER_SELECT": "चयन",
                "SELECT_GENDER_MALE": "पुरुष",
                "SELECT_GENDER_FEMALE": "महिला",
                "SELECT_GENDER_OTHERS": "अन्य लोग",
                "SELECT_SCHOLARSHIP_SELECT": "चयन",
                "SELECT_SCHOLARSHIP_COST": "लागत",
                "SELECT_SCHOLARSHIP_OTHER": "अन्य प्रकार",
                "SELECT_JOB_SELECT": "चयन",
                "SELECT_JOB_TAKEN": "नौकरी मिल गई",
                "SELECT_JOB_NOT_TAKEN": "नौकरी नहीं मिली",
                "SELECT_FEEDBACK_SELECT": "चयन",
                "SELECT_FEEDBACK_CENTERS": "केन्द्र",
                "SELECT_FEEDBACK_COURSES": "पाठ्यक्रम",
                "SELECT_FEEDBACK_SCHOLARSHIP": "छात्रवृत्ति",
                "SELECT_FEEDBACK_JOBS": "काम",
                "SELECT_FEEDBACK_OTHER": "अन्य प्रकार",
                "CENTER_SELECT_CITY": "शहर चुनें",
                "REGISTER_BUTTON_SUBMIT": "जमा करें",
                "MENU_IT_PARTNER": "आईटी साथी"
            },
            "mr": {
                "LOGIN_HEADER": "लॉगिन",
                "LOGIN_EMAIL_HINT": "ईमेल",
                "LOGIN_PASSWORD_HINT": "पासवर्ड",
                "LOGIN_BUTTON_SIGN_IN": "साइन इन",
                "LOGIN_BUTTON_SIGN_UP": "साइन अप",
                "LOGIN_FORGOT_PASSWORD": "पासवर्ड विसरला",
                "LOGIN_EMAIL_ERROR": "कृपया ईमेल प्रविष्ट करा",
                "LOGIN_PASSWORD_ERROR": "कृपया पासवर्ड प्रविष्ट करा",
                "REGISTER_HEADER": "साइनअप",
                "REGISTER_HEADER_PATIENT": "रुग्णाची माहिती",
                "REGISTER_PATIENT_NAME": "रुग्णाचे नाव",
                "REGISTER_PATIENT_NO": "रुग्णाचा क्रमांक",
                "REGISTER_PATIENT_RELATION": "रुग्णाशी संबंध",
                "REGISTER_PATIENT_ADDRESS": "रुग्णाचा पत्ता",
                "REGISTER_PATIENT_DETAILS": "रुग्णाचे तपशील",
                "REGISTER_PERSONAL_INFO": "वैयक्तिक माहिती",
                "REGISTER_NAME": "पहिले नाव",
                "REGISTER_LAST_NAME": "आडनाव",
                "REGISTER_AGE": "वय",
                "REGISTER_GENDER": "लिंग निवडा",
                "REGISTER_Qualification": "पात्रता",
                "REGISTER_EXPERIENCE": "अनुभव",
                "REGISTER_CONTACT_INFO": "संपर्क माहिती",
                "REGISTER_MOBILE_NO": "मोबाइल",
                "REGISTER_EMAIL": "ईमेल",
                "REGISTER_PASSWORD": "पासवर्ड",
                "REGISTER_CONFIRM_PASSWORD": "पासवर्डची पुष्टी करा",
                "REGISTER_STATE": "राज्य",
                "REGISTER_CITY": "शहर",
                "REGISTER_PINCODE": "पिन कोड",
                "REGISTER_OLD_ACCOUNT": "आधीपासूनच एक खाते आहे का",
                "REGISTER_BUTTON_SIN_IN": "साइन इन",
                "REGISTER_PATIENT_NAME_ERROR": "कृपया रुग्णाचे नाव प्रविष्ट करा",
                "REGISTER_PATIENT_NO_ERROR": "कृपया रुग्णाचा संपर्क क्रमांक प्रविष्ट करा",
                "REGISTER_PATIENT_RELATION_ERROR": "कृपया रुग्णासोबतचे संबंध प्रविष्ट करा",
                "REGISTER_PATIENT_ADDRESS_ERROR": "कृपया रुग्णाचा पत्ता रविष्ट करा",
                "REGISTER_PATIENT_DETAILS_ERROR": "कृपया रुग्णाचे तपशील प्रविष्ट करा",
                "REGISTER_NAME_ERROR": "कृपया नाव प्रविष्ट करा",
                "REGISTER_LAST_NAME_ERROR": "कृपया आडनाव प्रविष्ट कराकृपया आडनाव प्रविष्ट करा",
                "REGISTER_AGE_ERROR": "कृपया वय प्रविष्ट करा",
                "REGISTER_GENDER_ERROR": "कृपया लिंग निवडा",
                "REGISTER_QUALIFICATION_ERROR": "कृपया पात्रता प्रविष्ट करा",
                "REGISTER_EXPERIENCE_ERROR": "कृपया अनुभव प्रविष्ट करा",
                "REGISTER_MOBILE_NO_ERROR": "कृपया मोबाइल नंबर प्रविष्ट करा",
                "REGISTER_EMAIL_ERROR": "कृपया ईमेल प्रविष्ट कराकृपया ईमेल प्रविष्ट करा",
                "REGISTER_PASSWORD_ERROR": "कृपया पासवर्ड प्रविष्ट करा",
                "REGISTER_CONFIRM_PASSWORD_ERROR": "कृपया पासवर्डची पुष्टी करा",
                "REGISTER_MISMATCH_ERROR": "पासवर्ड जुळत नाही",
                "REGISTER_STATE_ERROR": "राज्य",
                "REGISTER_CITY_ERROR": "शहर",
                "REGISTER_PINCODE_ERROR": "पिन कोड",
                "FORGOT_HEADER": "पासवर्ड विसरला?",
                "FORGOT_EMAIL": "ईमेल",
                "FORGOT_EMAIL_ERROR": "कृपया ईमेल प्रविष्ट करा",
                "FORGOT_BUTTON_OK": "ठीक आहे",
                "FORGOT_BUTTON_CANCEL": "रद्द करा",
                "OLD_PASSWORD": "जुना पासवर्ड",
                "NEW_PASSWORD": "नवीन पासवर्ड",
                "CONFIRM_PASSWORD": "पासवर्डची पुष्टी करा",
                "OLD_PASSWORD_ERROR": "कृपया जुना पासवर्ड प्रविष्ट करा",
                "NEW_PASSWORD_ERROR": "कृपया नवीन पासवर्ड प्रविष्ट करा",
                "CHOOSE_LANGUAGE": "भाषा निवडा",
                "BUTTON_CONTINUE": "ठीक आहे",
                "LANGUAGE_ERROR": "कृपया भाषा निवडा",
                "BUTTON_UPDATE": "अद्ययावत करा",
                "BUTTON_CHANGE_PASSWORD": "पासवर्ड बदला",
                "LOADING_HEADER": "कृपया प्रतीक्षा करा",
                "LOGOUT_TITLE": "लॉगआउट करू इच्छिता",
                "CENTER_CONTACT_PERSON": "संपर्क व्यक्ती",
                "CENTER_NAME": "केंद्राचे नाव",
                "CENTER_STATE": "राज्य",
                "CENTER_DISTRICT": "जिल्हा",
                "CENTER_CITY": "शहर",
                "CENTER_ADDRESS": "पत्ता",
                "CENTER_ADDRESS1": "पत्ता-1",
                "CENTER_PHONE_NO": "फोन नंबर",
                "CENTER_EMAIL": "ईमेल",
                "CENTER_OTHER_DETAILS": "इतर तपशील",
                "CENTER_HINT": "कीवर्डद्वारे शोधा",
                "CENTER_SELECT": "राज्य निवडा",
                "MENU_HOME": "मुख्यपृष्ठ",
                "MENU_TRAINING": "प्रशिक्षण केंद्रे",
                "MENU_PROFILE": "प्रोफाइल",
                "MENU_DONATE": "दान करा",
                "MENU_ABOUT_US": "आमच्याबद्दल",
                "MENU_SCHOLARSHIP": "शिष्यवृत्ती फॉर्म",
                "MENU_LANGUAGE": "भाषा",
                "MENU_LOGOUT": "लॉग आउट",
                "MENU_SUGGESSTION": "सुचवलेली केन्द्रे",
                "MENU_JOB": "प्रशिक्षण / नोकरीची स्थिती",
                "MENU_FEEDBACK": "प्रतिक्रिया फॉर्म",
                "TRAINING_NAME": "प्रशिक्षण केंद्र",
                "TRAINING_NAME_ERROR": "प्रशिक्षण केंद्र प्रविष्ट करा",
                "TRAINING_COURSE": "कोर्स व्यस्त",
                "TRAINING_COURSE_ERROR": "कोर्स प्रविष्ट करा",
                "TRAINING_SCHOLARSHIP": "शिष्यवृत्ती निवडा",
                "TRAINING_SCHOLARSHIP_ERROR": "कृपया शिष्यवृत्ती निवडा",
                "TRAINING_START_DATE": "प्रारंभ तारीख",
                "TRAINING_START_DATE_ERROR": "प्रारंभ तारीख प्रविष्ट करा",
                "TRAINING_END_DATE": "पूर्ण झाले",
                "TRAINING_END_DATE_ERROR": "पूर्ण झाल्याची तारीख प्रविष्ट करा",
                "TRAINING_JOB": "नोकरी सुरु झाली",
                "TRAINING_JOB_ERROR": "जॉब / व्यवसायाची प्रारंभ तारीख प्रविष्ट करा",
                "TRAINING_JOB_TITLE": "नोकरीचे / व्यवसायाचे शीर्षक",
                "TRAINING_JOB_TITLE_ERROR": "कृपया नोकरी / व्यवसायाचे शीर्षक प्रविष्ट करा",
                "TRAINING_SALARY": "वेतन",
                "TRAINING_SALARY_ERROR": "वेतन प्रविष्ट करा",
                "FEEDBACK_TYPE": "निवडा प्रकार",
                "FEEDBACK_MESSAGE": "संदेश",
                "FEEDBACK_TYPE_ERROR": "कृपया प्रकार निवडा",
                "FEEDBACK_MESSAGE_ERROR": "कृपया संदेश प्रविष्ट करा",
                "FAMILY_INCOME": "कौटुंबिक उत्पन्न",
                "FAMILY_INCOME_ERROR": "कौटुंबिक उत्पन्न प्रविष्ट करा",
                "EARNING_MEMBER": "कमाऊ सदस्य",
                "EARNING_MEMBER_ERROR": "कमाऊ सदस्य प्रविष्ट करा",
                "PATIENT_RELATION": "रुग्णाशी संबंध",
                "PATIENT_RELATION_ERROR": "रुग्णाशी संबंध प्रविष्ट करा",
                "CENTER_CODE": "केंद्र कोड",
                "CENTER_CODE_ERROR": "केंद्र कोड प्रविष्ट करा",
                "CENTER_DETAILS": "केंद्र तपशील",
                "CENTER_DETAILS_ERROR": "केंद्र तपशील प्रविष्ट करा",
                "COURSE_TITLE": "कोर्स शीर्षक",
                "COURSE_TITLE_ERROR": "कोर्स शीर्षक प्रविष्ट करा",
                "COURSE_DETAILS": "कोर्स तपशील",
                "COURSE_DETAILS_ERROR": "कोर्स तपशील प्रविष्ट करा",
                "TRAINING_DURATION": "कोर्स कालावधी",
                "TRAINING_DURATION_ERROR": "कोर्स कालावधी प्रविष्ट करा",
                "TRAINING_COST": "प्रशिक्षण खर्च",
                "TRAINING_COST_ERROR": "प्रशिक्षण खर्च प्रविष्ट करा",
                "SCHOLARSHIP_TYPE": "निवडा प्रकार",
                "SCHOLARSHIP_TYPE_ERROR": "कृपया प्रकार निवडा",
                "SCHOLARSHIP_DETAILS": "शिष्यवृत्तीचा तपशील",
                "SCHOLARSHIP_DETAILS_ERROR": "शिष्यवृत्ती तपशील प्रविष्ट करा",
                "CONTACT_DETAILS": "संपर्क माहिती",
                "CONTACT_DETAILS_ERROR": "संपर्क तपशील प्रविष्ट करा",
                "LOGIN_EMAIL_VALID_ERROR": "लॉगिन ईमेल अवैध",
                "REGISTER_EMAIL_VALID_ERROR": "साइनअप ईमेल अवैध",
                "FORGORT_PASSWORD_VALID_ERROR": "अवैध पासवर्ड",
                "PASSWORD_MISMATCH": "पासवर्ड जुळत नाही",
                "CENTER_PIN_CODE": "मध्य पिनकोड",
                "NO_DATA": "माहिती उपलब्ध नाही",
                "START_DATE": "प्रारंभ तारीख",
                "END_DATE": "शेवटची तारीख",
                "JOB_DATE": "जॉबची प्रारंभ तारीख",
                "ERROR_NETWORK": "नेटवर्क त्रुटी",
                "SELECT_GENDER_SELECT": "निवडा",
                "SELECT_GENDER_MALE": "पुरुष",
                "SELECT_GENDER_FEMALE": "मादी",
                "SELECT_GENDER_OTHERS": "इतर",
                "SELECT_SCHOLARSHIP_SELECT": "निवडा",
                "SELECT_SCHOLARSHIP_COST": "किंमत",
                "SELECT_SCHOLARSHIP_OTHER": "इतर प्रकार",
                "SELECT_JOB_SELECT": "इतर",
                "SELECT_JOB_TAKEN": "नोकरी घेतली",
                "SELECT_JOB_NOT_TAKEN": "नोकरी घेतली नाही",
                "SELECT_FEEDBACK_SELECT": "इतर",
                "SELECT_FEEDBACK_CENTERS": "केंद्र",
                "SELECT_FEEDBACK_COURSES": "अभ्यासक्रम",
                "SELECT_FEEDBACK_SCHOLARSHIP": "शिष्यवृत्ती",
                "SELECT_FEEDBACK_JOBS": "नोकर्या",
                "SELECT_FEEDBACK_OTHER": "इतर",
                "CENTER_SELECT_CITY": "शहर निवडा",
                "REGISTER_BUTTON_SUBMIT": "सबमिट करा",
                "MENU_IT_PARTNER": "आयटी भागीदार"
            },
            "or": {
                "LOGIN_HEADER": "ଲୋଗ୍ ଇନ",
                "LOGIN_EMAIL_HINT": "ଇମେଲ",
                "LOGIN_PASSWORD_HINT": "ପାସୱାର୍ଡ",
                "LOGIN_BUTTON_SIGN_IN": "ସାଇନ୍ ଇନ କରନ୍ତୁ",
                "LOGIN_BUTTON_SIGN_UP": "ସାଇନ୍ ଅପ୍ କରନ୍ତୁ",
                "LOGIN_FORGOT_PASSWORD": "ପାସୱାର୍ଡ ଭୁଲିଗଲେ କି?",
                "LOGIN_EMAIL_ERROR": "ଇମେଲ୍ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "LOGIN_PASSWORD_ERROR": "ପାସୱାର୍ଡ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_HEADER": "ସାଇନ୍ ଅପ୍ ଫର୍ମ",
                "REGISTER_HEADER_PATIENT": "ରୋଗୀଙ୍କ ସୂଚନା",
                "REGISTER_PATIENT_NAME": "ରୋଗୀଙ୍କ ନାମ",
                "REGISTER_PATIENT_NO": "ରୋଗୀଙ୍କ ନମ୍ବର",
                "REGISTER_PATIENT_RELATION": "ରୋଗୀଙ୍କ ସହ ସମ୍ବନ୍ଧ",
                "REGISTER_PATIENT_ADDRESS": "ରୋଗୀଙ୍କ ଠିକଣା",
                "REGISTER_PATIENT_DETAILS": "ରୋଗୀଙ୍କ ସମସ୍ୟା",
                "REGISTER_PERSONAL_INFO": "ବ୍ୟକ୍ତିଗତ",
                "REGISTER_NAME": "ପ୍ରଥମ ନାମ",
                "REGISTER_LAST_NAME": "ଶେଷ ନାମ",
                "REGISTER_AGE": "ବୟସ",
                "REGISTER_GENDER": "ଲିଙ୍ଗ",
                "REGISTER_Qualification": "ଯୋଗ୍ୟତା",
                "REGISTER_EXPERIENCE": "ଅନୁଭବ",
                "REGISTER_CONTACT_INFO": "ସଂପର୍କ ଠିକଣା",
                "REGISTER_MOBILE_NO": "ମୋବାଇଲ",
                "REGISTER_EMAIL": "ଇମେଲ୍",
                "REGISTER_PASSWORD": "ପାସୱାର୍ଡ",
                "REGISTER_CONFIRM_PASSWORD": "ପାସୱାର୍ଡ ପୃଷ୍ଟି କରନ୍ତୁ",
                "REGISTER_STATE": "ରାଜ୍ୟ",
                "REGISTER_CITY": "ସହର",
                "REGISTER_PINCODE": "ପିନ୍ ନମ୍ବର",
                "REGISTER_OLD_ACCOUNT": "ଜମା କରନ୍ତୁ",
                "REGISTER_BUTTON_SIN_IN": "ଆପଣଙ୍କ ପାଖରେ ପୂର୍ବରୁ ଖାତା ଅଛି କି? ",
                "REGISTER_PATIENT_NAME_ERROR": "ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
                "REGISTER_PATIENT_NO_ERROR": "ରୋଗୀଙ୍କ ନାମ ଦିଅନ୍ତୁ",
                "REGISTER_PATIENT_RELATION_ERROR": "ରୋଗୀଙ୍କ ନମ୍ବର ଦିଅନ୍ତୁ",
                "REGISTER_PATIENT_ADDRESS_ERROR": "ଦୟାକରି ରୋଗୀଙ୍କ ସହ ସଂପର୍କ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_PATIENT_DETAILS_ERROR": "ଦୟାକରି ରୋଗୀଙ୍କ ଠିକଣା ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_NAME_ERROR": "ଦୟାକରି ରୋଗୀଙ୍କ ସମସ୍ୟା ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_LAST_NAME_ERROR": "ଦୟାକରି ଶେଷ ନାମ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_AGE_ERROR": "ଦୟାକରି ବୟସ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_GENDER_ERROR": "ଦୟାକରି ଲିଙ୍ଗ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_QUALIFICATION_ERROR": "ଦୟାକରି ଯୋଗ୍ୟତା ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_EXPERIENCE_ERROR": "ଦୟାକରି ଅନୁଭବ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_MOBILE_NO_ERROR": "ଦୟାକରି ମୋବାଇଲ ନମ୍ବର ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_EMAIL_ERROR": "ଦୟାକରି ଇମେଲ୍ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_PASSWORD_ERROR": "ଦୟାକରି ପାସୱାର୍ଡ ଦିଅନ୍ତୁ",
                "REGISTER_CONFIRM_PASSWORD_ERROR": "ଦୟାକରି ପାସୱାର୍ଡ ପୃଷ୍ଟି କରନ୍ତୁ",
                "REGISTER_MISMATCH_ERROR": "ପାସୱାର୍ଡ ର ମେଳ ହେଲା ନି",
                "REGISTER_STATE_ERROR": "ଦୟାକରି ସହର ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_CITY_ERROR": "ଦୟାକରି ସହର ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "REGISTER_PINCODE_ERROR": "ଦୟାକରି ପିନ୍ ନମ୍ବର ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "FORGOT_HEADER": "ପାସୱାର୍ଡ ଭୁଲି ଗଲେ କି?",
                "FORGOT_EMAIL": "ଇମେଲ୍",
                "FORGOT_EMAIL_ERROR": "ଦୟାକରି ଇମେଲ୍ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "FORGOT_BUTTON_OK": "ଆଗକୁ ବଢନ୍ତୁ",
                "FORGOT_BUTTON_CANCEL": "ରଦ୍ଦ କରନ୍ତୁ",
                "OLD_PASSWORD": "ପୁରୁଣା ପାସୱାର୍ଡ",
                "NEW_PASSWORD": "ନୂତନ ପାସୱାର୍ଡ",
                "CONFIRM_PASSWORD": "ପାସୱାର୍ଡ ପୃଷ୍ଟି କରନ୍ତୁ",
                "OLD_PASSWORD_ERROR": "ଦୟାକରି ପୁରୁଣା ପାସୱାର୍ଡ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "NEW_PASSWORD_ERROR": "ଦୟାକରି ନୂତନ ପାସୱାର୍ଡ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "CHOOSE_LANGUAGE": "ଭାଷା ବାଛନ୍ତୁ",
                "BUTTON_CONTINUE": "ଆଗକୁ ବଢନ୍ତୁ",
                "LANGUAGE_ERROR": "ଦୟାକରି ଭାଷା  ବାଛନ୍ତୁ",
                "BUTTON_UPDATE": "ଉପଦଟିଏ",
                "BUTTON_CHANGE_PASSWORD": "ପାସୱାର୍ଡ ବଦଳାନ୍ତୁ",
                "LOADING_HEADER": "ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ",
                "LOGOUT_TITLE": "ଲୋଗ୍ ଆଉଟ୍ କରିବାକୁ ଚାହାଁନ୍ତି କି?",
                "CENTER_CONTACT_PERSON": "ସଂପର୍କ ବ୍ୟକ୍ତି",
                "CENTER_NAME": "କେନ୍ଦ୍ର ର ନାମ",
                "CENTER_STATE": "ରାଜ୍ୟ",
                "CENTER_DISTRICT": "ଜିଲ୍ଲା",
                "CENTER_CITY": "ସହର",
                "CENTER_ADDRESS": "ଠିକଣା",
                "CENTER_ADDRESS1": "ଠିକଣା-୧",
                "CENTER_PHONE_NO": "ଦୂରଭାଷ",
                "CENTER_EMAIL": "ଇମେଲ୍",
                "CENTER_OTHER_DETAILS": "ଅନ୍ୟ ତଥ୍ଯ",
                "CENTER_HINT": "କେୟାୱର୍ଡ",
                "CENTER_SELECT": "ରାଜ୍ୟ ବାଛନ୍ତୁ",
                "MENU_HOME": "ହୋମ୍",
                "MENU_TRAINING": "ପ୍ରଶିକ୍ଷଣ",
                "MENU_PROFILE": "ପ୍ରୋଫାଇଲ୍",
                "MENU_DONATE": "ଦାନ କରନ୍ତୁ",
                "MENU_ABOUT_US": "ଆମ ସମ୍ବନ୍ଧରେ",
                "MENU_SCHOLARSHIP": "ଛାତ୍ରବୃତ୍ତି",
                "MENU_LANGUAGE": "ଭାଷା",
                "MENU_LOGOUT": "ଲୋଗ୍ ଆଉଟ୍",
                "MENU_SUGGESSTION": "ସୂଜଗେଷ୍ଟେଡ଼ ସେଣ୍ଟେଶ",
                "MENU_JOB": "ଚାକିରୀ",
                "MENU_FEEDBACK": "ପ୍ରତିକ୍ରିୟା",
                "TRAINING_NAME": "ପ୍ରଶିକ୍ଷଣ ର ନାମ",
                "TRAINING_NAME_ERROR": "ଦୟାକରି ପ୍ରଶିକ୍ଷଣ କେନ୍ଦ୍ର ର ନାମ",
                "TRAINING_COURSE": "ପାଠ୍ୟକ୍ରମ",
                "TRAINING_COURSE_ERROR": "ଦୟାକରି ପାଠ୍ୟକ୍ରମ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "TRAINING_SCHOLARSHIP": " ଛାତ୍ରବୃତ୍ତି ର ଚୟନ କରନ୍ତୁ",
                "TRAINING_SCHOLARSHIP_ERROR": "ଦୟାକରି ଛାତ୍ରବୃତ୍ତି ଚୟନ କରନ୍ତୁ",
                "TRAINING_START_DATE": "ଆରମ୍ଭ କରିବାର ତିଥି",
                "TRAINING_START_DATE_ERROR": "ଦୟାକରି ପ୍ରାରମ୍ଭ ତିଥି ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "TRAINING_END_DATE": "ସଂପନ୍ନ ତିଥି",
                "TRAINING_END_DATE_ERROR": "ଶେଷ ହେବାର ତାରିଖ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "TRAINING_JOB": "ଚାକିରୀ ଆରମ୍ଭ ହେଲା",
                "TRAINING_JOB_ERROR": "ଚାକିରୀର ଆରମ୍ଭ ତିଥି ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "TRAINING_JOB_TITLE": "ଚାକିରୀ/ବ୍ୟାପାର ଶୀର୍ଷକ",
                "TRAINING_JOB_TITLE_ERROR": "ଦୟାକରି ଚାକିରୀ/ବ୍ୟାପାର ଶୀର୍ଷକ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "TRAINING_SALARY": "ବେତନ",
                "TRAINING_SALARY_ERROR": "ଦୟାକରି ବେତନ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "FEEDBACK_TYPE": "ପ୍ରକାର ବାଛନ୍ତୁ",
                "FEEDBACK_MESSAGE": "ସନ୍ଦେଶ",
                "FEEDBACK_TYPE_ERROR": "ଦୟାକରି ପ୍ରକାରର ଚୟନ କରନ୍ତୁ",
                "FEEDBACK_MESSAGE_ERROR": "ଦୟାକରି ସନ୍ଦେଶ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "FAMILY_INCOME": "ପାରିବାରିକ ଆୟ",
                "FAMILY_INCOME_ERROR": "ଦୟାକରି ପାରିବାରିକ ଆୟ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "EARNING_MEMBER": "ଆୟ କରୁଥିବା ସଦସ୍ୟ",
                "EARNING_MEMBER_ERROR": "ଦୟାକରି ଆୟ କରୁଥିବା ସଦସ୍ୟ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "PATIENT_RELATION": "ରୋଗୀଙ୍କ ସହ ସଂପର୍କ",
                "PATIENT_RELATION_ERROR": "ଦୟାକରି ରୋଗୀଙ୍କ ସହ ସଂପର୍କ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "CENTER_CODE": "କେନ୍ଦ୍ରର ପିନ୍ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "CENTER_CODE_ERROR": "ଦୟାକରି କେନ୍ଦ୍ରର ପିନ୍ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "CENTER_DETAILS": "କେନ୍ଦ୍ର ବିବରଣୀ",
                "CENTER_DETAILS_ERROR": "ଦୟାକରି କେନ୍ଦ୍ର ବିବରଣୀ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "COURSE_TITLE": "ପାଠ୍ୟକ୍ରମର ବିଷୟ",
                "COURSE_TITLE_ERROR": "ଦୟାକରି ପାଠ୍ୟକ୍ରମର ବିଷୟ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "COURSE_DETAILS": "ପାଠ୍ୟକ୍ରମ ବିବରଣୀ",
                "COURSE_DETAILS_ERROR": "ପାଠ୍ୟକ୍ରମ ବିବରଣୀ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "TRAINING_DURATION": "ପ୍ରଶିକ୍ଷଣ ଅବଧି",
                "TRAINING_DURATION_ERROR": "ପ୍ରଶିକ୍ଷଣ ଅବଧି ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "TRAINING_COST": "ପ୍ରଶିକ୍ଷଣ ଖର୍ଚ୍ଚ",
                "TRAINING_COST_ERROR": "ପ୍ରଶିକ୍ଷଣ ଖର୍ଚ୍ଚ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "SCHOLARSHIP_TYPE": "ପ୍ରକାର ବାଛନ୍ତୁ",
                "SCHOLARSHIP_TYPE_ERROR": "ଦୟାକରି ପ୍ରକାରର ବାଛନ୍ତୁ",
                "SCHOLARSHIP_DETAILS": "ଛାତ୍ରବୃତ୍ତି ବିବରଣୀ",
                "SCHOLARSHIP_DETAILS_ERROR": "ଛାତ୍ରବୃତ୍ତି ବିବରଣୀ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "CONTACT_DETAILS": "ସଂପର୍କ ବିବରଣୀ",
                "CONTACT_DETAILS_ERROR": "ଦୟାକରି ସଂପର୍କ ବିବରଣୀ ଉଲ୍ଲେଖ କରନ୍ତୁ",
                "LOGIN_EMAIL_VALID_ERROR": "ଏରରର",
                "REGISTER_EMAIL_VALID_ERROR": "ଏରରର",
                "FORGORT_PASSWORD_VALID_ERROR": "ଏରରର",
                "PASSWORD_MISMATCH": "ମିସ୍ମ୍ତଚ",
                "CENTER_PIN_CODE": "ପିନ୍ ନମ୍ବର",
                "NO_DATA": "ଏରରର",
                "START_DATE": "ବେଗଈଂ ଡଟ",
                "END_DATE": "ଏଣ୍ଡ ଡଟ",
                "JOB_DATE": "ଜବ ଡଟ",
                "ERROR_NETWORK": "ନେଟୱର୍କ ଏରରର",
                "SELECT_GENDER_SELECT": "ସେଲେସତ",
                "SELECT_GENDER_MALE": "ମଲେ",
                "SELECT_GENDER_FEMALE": "ଫେମଲେ",
                "SELECT_GENDER_OTHERS": "ଓଠେର୍ସ",
                "SELECT_SCHOLARSHIP_SELECT": "ସେଲେସତ",
                "SELECT_SCHOLARSHIP_COST": "କଷ୍ଟ",
                "SELECT_SCHOLARSHIP_OTHER": "ଓଠେର୍ସ",
                "SELECT_JOB_SELECT": "ସେଲେସତ",
                "SELECT_JOB_TAKEN": "ଜବ ତାକେନ",
                "SELECT_JOB_NOT_TAKEN": "ଜବ ନୋଟ ତାକେନ",
                "SELECT_FEEDBACK_SELECT": "ସେଲେସତ",
                "SELECT_FEEDBACK_CENTERS": "ସେଣ୍ଟେଶ",
                "SELECT_FEEDBACK_COURSES": "ଚୋୖର୍ଶେସ",
                "SELECT_FEEDBACK_SCHOLARSHIP": "ସଚୋଲରସହିପ",
                "SELECT_FEEDBACK_JOBS": "ଜବ୍ସ",
                "SELECT_FEEDBACK_OTHER": "ଓଠେର୍ସ",
                "CENTER_SELECT_CITY": "ସହର",
                "REGISTER_BUTTON_SUBMIT": "ସୁବିମ୍ୱିତ",
                "MENU_IT_PARTNER": "ଇଟା PARTNER"
            },
            "pu": {
                "LOGIN_HEADER": "ਲਾਗਿਨ",
                "LOGIN_EMAIL_HINT": "ਈ - ਮੇਲ",
                "LOGIN_PASSWORD_HINT": "ਪਾਸਵਰਡ",
                "LOGIN_BUTTON_SIGN_IN": "ਸਾਈਨ - ਇਨ",
                "LOGIN_BUTTON_SIGN_UP": "ਸਾਇਨ ਅਪ",
                "LOGIN_FORGOT_PASSWORD": "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ",
                "LOGIN_EMAIL_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ਦਾਖਲ ਕਰੋ",
                "LOGIN_PASSWORD_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ਦਾਖਲ ਕਰੋ",
                "REGISTER_HEADER": "ਸਾਇਨ ਅਪ",
                "REGISTER_HEADER_PATIENT": "ਮਰੀਜ਼ ਜਾਣਕਾਰੀ",
                "REGISTER_PATIENT_NAME": "ਮਰੀਜ਼ ਦਾ ਨਾਂ",
                "REGISTER_PATIENT_NO": "ਮਰੀਜ਼ ਸੰਪਰਕ ਨੰਬਰ",
                "REGISTER_PATIENT_RELATION": "ਮਰੀਜ਼ ਨਾਲ ਰਿਸ਼ਤਾ",
                "REGISTER_PATIENT_ADDRESS": "ਮਰੀਜ਼ ਦਾ ਪਤਾ",
                "REGISTER_PATIENT_DETAILS": "ਮਰੀਜ਼ ਦੀ ਬੀਮਾਰੀ",
                "REGISTER_PERSONAL_INFO": "ਵਿਅਕਤੀਗਤ ਜਾਣਕਾਰੀ",
                "REGISTER_NAME": "ਨਾਮ",
                "REGISTER_LAST_NAME": "ਆਖਰੀ ਨਾਂਮ",
                "REGISTER_AGE": "ਉਮਰ",
                "REGISTER_GENDER": "ਲਿੰਗ ਚੁਣੋ",
                "REGISTER_Qualification": "ਯੋਗਤਾ",
                "REGISTER_EXPERIENCE": "ਅਨੁਭਵ",
                "REGISTER_CONTACT_INFO": "ਸੰਪਰਕ ਜਾਣਕਾਰੀ",
                "REGISTER_MOBILE_NO": "ਮੋਬਾਈਲ",
                "REGISTER_EMAIL": "ਈ - ਮੇਲ",
                "REGISTER_PASSWORD": "ਪਾਸਵਰਡ",
                "REGISTER_CONFIRM_PASSWORD": "ਪਾਸਵਰਡ ਪੱਕਾ ਕਰੋ",
                "REGISTER_STATE": "ਰਾਜ",
                "REGISTER_CITY": "ਸ਼ਹਿਰ",
                "REGISTER_PINCODE": "ਪਿੰਨ ਕੋਡ",
                "REGISTER_OLD_ACCOUNT": "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
                "REGISTER_BUTTON_SIN_IN": "ਸਾਈਨ - ਇਨ",
                "REGISTER_PATIENT_NAME_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਮਰੀਜ਼ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ",
                "REGISTER_PATIENT_NO_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਮਰੀਜ਼ ਨੂੰ ਮੋਬਾਇਲ ਦਿਓ",
                "REGISTER_PATIENT_RELATION_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਮਰੀਜ਼ ਸੰਬੰਧ ਦਰਜ ਕਰੋ",
                "REGISTER_PATIENT_ADDRESS_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਮਰੀਜ਼ ਨੂੰ ਪਤਾ ਦਾਖਲ ਕਰੋ",
                "REGISTER_PATIENT_DETAILS_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਮਰੀਜ਼ ਦੀ ਬਿਮਾਰੀ ਦਰਜ ਕਰੋ",
                "REGISTER_NAME_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਨਾਮ ਦਰਜ ਕਰੋ",
                "REGISTER_LAST_NAME_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਆਖਰੀ ਨਾਮ ਦਰਜ ਕਰੋ",
                "REGISTER_AGE_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਉਮਰ ਦਿਓ",
                "REGISTER_GENDER_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਲਿੰਗ ਚੁਣੋ",
                "REGISTER_QUALIFICATION_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਯੋਗਤਾ ਦਰਜ ਕਰੋ",
                "REGISTER_EXPERIENCE_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਤਜਰਬਾ ਦਰਜ ਕਰੋ",
                "REGISTER_MOBILE_NO_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਤਜਰਬਾ ਦਰਜ ਕਰੋ",
                "REGISTER_EMAIL_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ਦਾਖਲ ਕਰੋ",
                "REGISTER_PASSWORD_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ",
                "REGISTER_CONFIRM_PASSWORD_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ",
                "REGISTER_MISMATCH_ERROR": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ",
                "REGISTER_STATE_ERROR": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ",
                "REGISTER_CITY_ERROR": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ",
                "REGISTER_PINCODE_ERROR": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ",
                "FORGOT_HEADER": "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
                "FORGOT_EMAIL": "ਈ - ਮੇਲ",
                "FORGOT_EMAIL_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ਦਾਖਲ ਕਰੋ",
                "FORGOT_BUTTON_OK": "ਠੀਕ ਹੈ",
                "FORGOT_BUTTON_CANCEL": "ਰੱਦ ਕਰੋ",
                "OLD_PASSWORD": "ਪੁਰਾਣਾ ਪਾਸਵਰਡ",
                "NEW_PASSWORD": "ਨਵਾਂ ਪਾਸਵਰਡ",
                "CONFIRM_PASSWORD": "ਪਾਸਵਰਡ ਪੱਕਾ ਕਰੋ",
                "OLD_PASSWORD_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਪੁਰਾਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
                "NEW_PASSWORD_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
                "CHOOSE_LANGUAGE": "ਭਾਸ਼ਾ ਚੁਣੋ",
                "BUTTON_CONTINUE": "ਜਾਰੀ ਰੱਖੋ",
                "LANGUAGE_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਭਾਸ਼ਾ ਚੁਣੋ",
                "BUTTON_UPDATE": "ਅੱਪਡੇਟ ਕਰੋ",
                "BUTTON_CHANGE_PASSWORD": "ਪਾਸਵਰਡ ਬਦਲੋ",
                "LOADING_HEADER": "ਕ੍ਰਿਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ",
                "LOGOUT_TITLE": "ਕੀ ਤੁਸੀਂ ਲਾਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
                "CENTER_CONTACT_PERSON": "ਵਿਅਕਤੀ ਨੂੰ ਸੰਪਰਕ ਕਰੋ",
                "CENTER_NAME": "ਸੈਂਟਰ ਦਾ ਨਾਮ",
                "CENTER_STATE": "ਰਾਜ",
                "CENTER_DISTRICT": "ਜ਼ਿਲ੍ਹਾ",
                "CENTER_CITY": "ਸ਼ਹਿਰ",
                "CENTER_ADDRESS": "ਪਤਾ",
                "CENTER_ADDRESS1": "ਪਤਾ-1",
                "CENTER_PHONE_NO": "ਫੋਨ ਨੰਬਰ",
                "CENTER_EMAIL": "ਈ - ਮੇਲ",
                "CENTER_OTHER_DETAILS": "ਹੋਰ ਵੇਰਵੇ",
                "CENTER_HINT": "ਕੀਵਰਡ ਦੁਆਰਾ ਖੋਜ ਕਰੋ",
                "CENTER_SELECT": "ਰਾਜ ਦੀ ਚੋਣ ਕਰੋ",
                "MENU_HOME": "ਹੋਮਪੇਜ",
                "MENU_TRAINING": "ਸਿਖਲਾਈ ਕੇਂਦਰ",
                "MENU_PROFILE": "ਪ੍ਰੋਫਾਇਲ",
                "MENU_DONATE": "ਦਾਨ ਕਰੋ",
                "MENU_ABOUT_US": "ਸਾਡੇ ਬਾਰੇ",
                "MENU_SCHOLARSHIP": "ਸਕਾਲਰਸ਼ਿਪ ਫਾਰਮ",
                "MENU_LANGUAGE": "ਭਾਸ਼ਾ",
                "MENU_LOGOUT": "ਲਾਗਆਉਟ",
                "MENU_SUGGESSTION": "ਸੁਝਾਏ ਗਏ ਕੇਂਦਰਾਂ",
                "MENU_JOB": "ਸਿਖਲਾਈ / ਨੌਕਰੀ ਦੀ ਸਥਿਤੀ",
                "MENU_FEEDBACK": "ਫੀਡਬੈਕ ਫਾਰਮ",
                "TRAINING_NAME": "ਸਿਖਲਾਈ ਕੇਂਦਰ",
                "TRAINING_NAME_ERROR": "ਸਿਖਲਾਈ ਕੇਂਦਰ ਦਾਖਲ ਕਰੋ",
                "TRAINING_COURSE": "ਕੋਰਸ ਨਾਲ ਜੁੜਿਆ",
                "TRAINING_COURSE_ERROR": "ਕੋਰਸ ਵਿੱਚ ਰੁਝੇਵੇਂ ਦਾਖਲ ਕਰੋ",
                "TRAINING_SCHOLARSHIP": "ਸਕਾਲਰਸ਼ਿਪ ਦੀ ਚੋਣ ਕਰੋ",
                "TRAINING_SCHOLARSHIP_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਸਕਾਲਰਸ਼ਿਪ ਚੁਣੋ",
                "TRAINING_START_DATE": "ਕਿਰਪਾ ਕਰਕੇ ਸਕਾਲਰਸ਼ਿਪ ਚੁਣੋ",
                "TRAINING_START_DATE_ERROR": "ਕੋਰਸ ਸ਼ੁਰੂ ਕਰਨ ਦੀ ਤਾਰੀਖ ਦਰਜ ਕਰੋ",
                "TRAINING_END_DATE": "ਕੋਰਸ ਸ਼ੁਰੂ ਕਰਨ ਦੀ ਤਾਰੀਖ ਦਰਜ ਕਰੋ",
                "TRAINING_END_DATE_ERROR": "ਕੋਰਸ ਪੂਰਾ ਹੋਣ ਦੀ ਤਾਰੀਖ ਦਾਖਲ ਕਰੋ",
                "TRAINING_JOB": "ਨੌਕਰੀ / ਕਾਰੋਬਾਰ ਦੀ ਸ਼ੁਰੂਆਤੀ ਤਾਰੀਖ",
                "TRAINING_JOB_ERROR": "ਨੌਕਰੀ / ਕਾਰੋਬਾਰ ਦੀ ਸ਼ੁਰੂਆਤ ਦੀ ਤਾਰੀਖ ਦਰਜ ਕਰੋ",
                "TRAINING_JOB_TITLE": "ਨੌਕਰੀ / ਕਾਰੋਬਾਰ ਦਾ ਟਾਈਟਲ ਦਾਖਲ ਕਰੋ",
                "TRAINING_JOB_TITLE_ERROR": "ਨੌਕਰੀ / ਕਾਰੋਬਾਰ ਦਾ ਟਾਈਟਲ ਦਾਖਲ ਕਰੋ",
                "TRAINING_SALARY": "ਤਨਖਾਹ",
                "TRAINING_SALARY_ERROR": "ਤਨਖਾਹ ਦਾਖਲ ਕਰੋ",
                "FEEDBACK_TYPE": "ਕਿਸਮ ਚੁਣੋ",
                "FEEDBACK_MESSAGE": "ਸੁਨੇਹਾ",
                "FEEDBACK_TYPE_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਪ੍ਰਕਾਰ ਚੁਣੋ",
                "FEEDBACK_MESSAGE_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਸੰਦੇਸ਼ ਦਾਖਲ ਕਰੋ",
                "FAMILY_INCOME": "ਪਰਿਵਾਰ ਦੀ ਆਮਦਨੀ",
                "FAMILY_INCOME_ERROR": "ਪਰਿਵਾਰ ਦੀ ਆਮਦਨ ਦਰਜ ਕਰੋ",
                "EARNING_MEMBER": "ਕਮਾਈ ਕਰਨ ਵਾਲੇ ਮੈਂਬਰ",
                "EARNING_MEMBER_ERROR": "ਕਮਾਈ ਕਰਨ ਵਾਲੇ ਮੈਂਬਰ ਨੂੰ ਦਾਖਲ ਕਰੋ",
                "PATIENT_RELATION": "ਮਰੀਜ਼ ਸੰਬੰਧ",
                "PATIENT_RELATION_ERROR": "ਮਰੀਜ਼ ਸੰਬੰਧ ਦਰਜ ਕਰੋ",
                "CENTER_CODE": "ਸੈਂਟਰ ਕੋਡ",
                "CENTER_CODE_ERROR": "ਸੈਂਟਰ ਕੋਡ ਦਾਖਲ ਕਰੋ",
                "CENTER_DETAILS": "ਸੈਂਟਰ ਦੇ ਵੇਰਵੇ",
                "CENTER_DETAILS_ERROR": "ਸੈਂਟਰ ਦੇ ਵੇਰਵੇ ਦਾਖਲ ਕਰੋ",
                "COURSE_TITLE": "ਕੋਰਸ ਦਾ ਸਿਰਲੇਖ",
                "COURSE_TITLE_ERROR": "ਕੋਰਸ ਦਾ ਸਿਰਲੇਖ ਦਿਓ",
                "COURSE_DETAILS": "ਕੋਰਸ ਦਾ ਸਿਰਲੇਖ ਦਿਓ",
                "COURSE_DETAILS_ERROR": "ਕੋਰਸ ਦਾ ਵੇਰਵਾ ਦਿਓ",
                "TRAINING_DURATION": "ਸਿਖਲਾਈ ਦੀ ਮਿਆਦ",
                "TRAINING_DURATION_ERROR": "ਸਿਖਲਾਈ ਮਿਆਦ ਦਾਖਲ ਕਰੋ",
                "TRAINING_COST": "ਸਿਖਲਾਈ ਦੀ ਲਾਗਤ",
                "TRAINING_COST_ERROR": "ਸਿਖਲਾਈ ਦੀ ਲਾਗਤ ਦਾਖਲ ਕਰੋ",
                "SCHOLARSHIP_TYPE": "ਕਿਸਮ ਚੁਣੋ",
                "SCHOLARSHIP_TYPE_ERROR": "ਕਿਰਪਾ ਕਰਕੇ ਪ੍ਰਕਾਰ ਚੁਣੋ",
                "SCHOLARSHIP_DETAILS": "ਸਕਾਲਰਸ਼ਿਪ ਦੇ ਵੇਰਵੇ",
                "SCHOLARSHIP_DETAILS_ERROR": "ਸਕਾਲਰਸ਼ਿਪ ਦੇ ਵੇਰਵੇ ਦਾਖਲ ਕਰੋ",
                "CONTACT_DETAILS": "ਸੰਪਰਕ ਵੇਰਵੇ",
                "CONTACT_DETAILS_ERROR": "ਸੰਪਰਕ ਵੇਰਵੇ ਦਾਖਲ ਕਰੋ",
                "LOGIN_EMAIL_VALID_ERROR": "ਗਲਤ ਈਮੇਲ",
                "REGISTER_EMAIL_VALID_ERROR": "ਗਲਤ ਈਮੇਲ",
                "FORGORT_PASSWORD_VALID_ERROR": "ਗਲਤ ਪਾਸਵਰਡ",
                "PASSWORD_MISMATCH": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ",
                "CENTER_PIN_CODE": "ਸੈਂਟਰ ਪਿੰਨ ਕੋਡ",
                "NO_DATA": "ਕੋਈ ਡਾਟਾ ਨਹੀਂ",
                "START_DATE": "ਤਾਰੀਖ ਸ਼ੁਰੂ",
                "END_DATE": "ਸਮਾਪਤੀ ਮਿਤੀ",
                "JOB_DATE": "ਨੌਕਰੀ ਦੀ ਤਾਰੀਖ",
                "ERROR_NETWORK": "ਨੈਟਵਰਕ ਅਸ਼ੁੱਧੀ",
                "SELECT_GENDER_SELECT": "ਚੁਣੋ",
                "SELECT_GENDER_MALE": "ਮਰਦ",
                "SELECT_GENDER_FEMALE": "ਮਾਦਾ",
                "SELECT_GENDER_OTHERS": "ਹੋਰ",
                "SELECT_SCHOLARSHIP_SELECT": "ਚੁਣੋ",
                "SELECT_SCHOLARSHIP_COST": "ਸਕਾਲਰਸ਼ਿਪ",
                "SELECT_SCHOLARSHIP_OTHER": "ਹੋਰ",
                "SELECT_JOB_SELECT": "ਚੁਣੋ",
                "SELECT_JOB_TAKEN": "ਨੌਕਰੀ ਲਿਆ",
                "SELECT_JOB_NOT_TAKEN": "ਨੌਕਰੀ ਨਹੀਂ ਲਈ ਗਈ",
                "SELECT_FEEDBACK_SELECT": "ਚੁਣੋ",
                "SELECT_FEEDBACK_CENTERS": "ਸੈਂਟਰ",
                "SELECT_FEEDBACK_COURSES": "ਕੋਰਸ",
                "SELECT_FEEDBACK_SCHOLARSHIP": "ਸਕਾਲਰਸ਼ਿਪ",
                "SELECT_FEEDBACK_JOBS": "ਨੌਕਰੀਆਂ",
                "SELECT_FEEDBACK_OTHER": "ਹੋਰ",
                "CENTER_SELECT_CITY": "ਸ਼ਹਿਰ ਦੀ ਚੋਣ ਕਰੋ",
                "REGISTER_BUTTON_SUBMIT": "ਜਮ੍ਹਾਂ ਕਰੋ",
                "MENU_IT_PARTNER": "IT ਪਾਰਟਨਰ"
            },
            "te": {
                "MENU_IT_PARTNER": "IT భాగస్వామి"
            }
        },
        "httpCode": "200"
    }
}

{
    "response": {
        "message": "Invalid Parameters",
        "body": {
            "family_income": [
                "The family income field is required."
            ],
            "earning_members": [
                "The earning members field is required."
            ],
            "patient_relationship": [
                "The patient relationship field is required."
            ],
            "center_code": [
                "The center code field is required."
            ],
            "center_details": [
                "The center details field is required."
            ],
            "course_title": [
                "The course title field is required."
            ],
            "course_details": [
                "The course details field is required."
            ],
            "training_duration": [
                "The training duration field is required."
            ],
            "training_cost": [
                "The training cost field is required."
            ],
            "scholarship_type": [
                "The scholarship type field is required."
            ],
            "scholarship_detail": [
                "The scholarship detail field is required."
            ],
            "center_poc": [
                "The center poc field is required."
            ],
            "user_id": [
                "The user id field is required."
            ],
            "language": [
                "The language field is required."
            ]
        },
        "httpCode": "400"
    }
}