Center<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

</body>
</html>


{
    "response": {
        "message": "Languages",
        "body": {
            "en": {
                "LOGIN_HEADER": "Login",
                "LOGIN_EMAIL_HINT": "Email",
                "LOGIN_PASSWORD_HINT": "Password",
                "LOGIN_BUTTON_SIGN_IN": "Sign In",
                "LOGIN_BUTTON_SIGN_UP": "Sign Up",
                "LOGIN_FORGOT_PASSWORD": "Forgot Password?",
                "LOGIN_EMAIL_ERROR": "Please enter Email",
                "LOGIN_PASSWORD_ERROR": "Please enter Password",
                "REGISTER_HEADER": "Sign Up",
                "REGISTER_HEADER_PATIENT": "Patient Information",
                "REGISTER_PATIENT_NAME": "Patient Name",
                "REGISTER_PATIENT_NO": "Patient Contact Number",
                "REGISTER_PATIENT_RELATION": "Relationship with Patient",
                "REGISTER_PATIENT_ADDRESS": "Patient Address",
                "REGISTER_PATIENT_DETAILS": "Details about Patient's Illness",
                "REGISTER_PERSONAL_INFO": "Personal Information",
                "REGISTER_NAME": "First Name",
                "REGISTER_LAST_NAME": "Last Name",
                "REGISTER_AGE": "Age",
                "REGISTER_GENDER": "Select Gender",
                "REGISTER_Qualification": "Qualification",
                "REGISTER_EXPERIENCE": "Experience",
                "REGISTER_CONTACT_INFO": "Contact Information",
                "REGISTER_MOBILE_NO": "Mobile",
                "REGISTER_EMAIL": "E-mail",
                "REGISTER_PASSWORD": "Password",
                "REGISTER_CONFIRM_PASSWORD": "Confirm password",
                "REGISTER_STATE": "State",
                "REGISTER_CITY": "City",
                "REGISTER_PINCODE": "Pin Code",
                "REGISTER_OLD_ACCOUNT": "Already have an account?",
                "REGISTER_BUTTON_SIN_IN": "Sign In",
                
                "REGISTER_PATIENT_NAME_ERROR": "Please enter patient Name",
                "REGISTER_PATIENT_NO_ERROR": "Please enter patient Contact Number",
                "REGISTER_PATIENT_RELATION_ERROR": "Please enter patient Relation",
                "REGISTER_PATIENT_ADDRESS_ERROR": "Please enter patient Address",
                "REGISTER_PATIENT_DETAILS_ERROR": "Please enter patient details",
                "REGISTER_NAME_ERROR": "Please enter Name",
                "REGISTER_LAST_NAME_ERROR": "Please enter  Last Name",
                "REGISTER_AGE_ERROR": "Please enter age",
                "REGISTER_GENDER_ERROR": "Please select Gender",
                "REGISTER_QUALIFICATION_ERROR": "Please enter Qualification",
                "REGISTER_EXPERIENCE_ERROR": "Please enter Experience",
                "REGISTER_MOBILE_NO_ERROR": "Please enter Mobile No",
                "REGISTER_EMAIL_ERROR": "Please enter Email",
                "REGISTER_PASSWORD_ERROR": "Please enter Password",
                "REGISTER_CONFIRM_PASSWORD_ERROR": "Please confirm Password",
                "REGISTER_MISMATCH_ERROR": "Password mismatch",
                "REGISTER_STATE_ERROR": "Please enter State",
                "REGISTER_CITY_ERROR": "Please enter City",
                "REGISTER_PINCODE_ERROR": "Please enter Pincode",
                "FORGOT_HEADER": "Forgot Password",
                "FORGOT_EMAIL": "Email",
                "FORGOT_EMAIL_ERROR": "Please enter email",
                "FORGOT_BUTTON_OK": "OK",
                "FORGOT_BUTTON_CANCEL": "Cancel",
                "OLD_PASSWORD": "Old password",
                "NEW_PASSWORD": "New Password",
                "CONFIRM_PASSWORD": "Confirm Password",
                "OLD_PASSWORD_ERROR": "Please enter old password",
                "NEW_PASSWORD_ERROR": "Please enter New Password",
                "CHOOSE_LANGUAGE": "Choose Language",
                "BUTTON_CONTINUE": "Continue",
                "LANGUAGE_ERROR": "Please Select Language",
                "BUTTON_UPDATE": "Update",
                "BUTTON_CHANGE_PASSWORD": "Change Password",
                "LOADING_HEADER": "Please wait ",
                "LOGOUT_TITLE": "Are you sure you want to Logout?",
                "CENTER_CONTACT_PERSON": "Contact person",
                "CENTER_NAME": "Centre Name",
                "CENTER_STATE": "State",
                "CENTER_DISTRICT": "District",
                "CENTER_CITY": "City",
                "CENTER_ADDRESS": "Address",
                "CENTER_ADDRESS1": "Address 1",
                "CENTER_PHONE_NO": "Phone No",
                "CENTER_EMAIL": "Email",
                "CENTER_OTHER_DETAILS": "Other Details",
                "CENTER_HINT": "Search by Keyword",
                "CENTER_SELECT": "Select state",
                "MENU_HOME": "Home",
                "MENU_TRAINING": "Training Centres",
                "MENU_PROFILE": "Profile",
                "MENU_DONATE": "Donate",
                "MENU_ABOUT_US": "About Us",
                "MENU_SCHOLARSHIP": "Scholarship Form",
                "MENU_LANGUAGE": "Language",
                "MENU_LOGOUT": "Logout",
                "MENU_SUGGESSTION": "Suggested Centres",
                "MENU_JOB": "Training/Job Status",
                "MENU_FEEDBACK": "Feedback Form",
                "TRAINING_NAME": "Training Centre",
                "TRAINING_NAME_ERROR": "Please enter training center name",
                "TRAINING_COURSE": "Course engaged",
                "TRAINING_COURSE_ERROR": "Please enter Course",
                "TRAINING_SCHOLARSHIP": "Select scholarship",
                "TRAINING_SCHOLARSHIP_ERROR": "Please Select scholarship",
                "TRAINING_START_DATE": "Training Start Date",
                "TRAINING_START_DATE_ERROR": "Please enter start date",
                "TRAINING_END_DATE": "Training Completion Date",
                "TRAINING_END_DATE_ERROR": "Please enter Completed date",
                "TRAINING_JOB": "Job/Business Start Date",
                "TRAINING_JOB_ERROR": "Please enter job/business started date",
                "TRAINING_JOB_TITLE": "Job/ Business Title",
                "TRAINING_JOB_TITLE_ERROR": "Please enter Job/ Business Title",
                "TRAINING_SALARY": "Salary",
                "TRAINING_SALARY_ERROR": "Please enter Salary",
                "FEEDBACK_TYPE": "Select Type",
                "FEEDBACK_MESSAGE": "Message",
                "FEEDBACK_TYPE_ERROR": "Please select type",
                "FEEDBACK_MESSAGE_ERROR": "Please enter message",
                "FAMILY_INCOME": "Family Income",
                "FAMILY_INCOME_ERROR": "Please enter Family Income",
                "EARNING_MEMBER": "Earning Member's Name",
                "EARNING_MEMBER_ERROR": "Please enter Earning member",
                "PATIENT_RELATION": "Relationship with Patient",
                "PATIENT_RELATION_ERROR": "Please enter Patient  Relation",
                "CENTER_CODE": "Center code",
                "CENTER_CODE_ERROR": "Please enter Center code",
                "CENTER_DETAILS": "Center details",
                "CENTER_DETAILS_ERROR": "Please enter Center details",
                "COURSE_TITLE": "Course Title",
                "COURSE_TITLE_ERROR": "Please enter course title",
                "COURSE_DETAILS": "Course details",
                "COURSE_DETAILS_ERROR": "Please enter Course details",
                "TRAINING_DURATION": "Training duration",
                "TRAINING_DURATION_ERROR": "Please enter Training duration",
                "TRAINING_COST": "Training cost",
                "TRAINING_COST_ERROR": "Please enter Training cost",
                "SCHOLARSHIP_TYPE": "Select Type",
                "SCHOLARSHIP_TYPE_ERROR": "Please Select Type",
                "SCHOLARSHIP_DETAILS": "Scholarship Details",
                "SCHOLARSHIP_DETAILS_ERROR": "Please enter Scholarship Details",
                "CONTACT_DETAILS": "Contact details",
                "CONTACT_DETAILS_ERROR": "Please enter Contact details",
                "LOGIN_EMAIL_VALID_ERROR": "Please enter valid Email",
                "REGISTER_EMAIL_VALID_ERROR": "Please enter Valid Email",
                "FORGORT_PASSWORD_VALID_ERROR": "Please enter Valid Password",
                "PASSWORD_MISMATCH": "Password mismatch",
                "CENTER_PIN_CODE": "Pin Code",
                "NO_DATA": "No Data Found",
                "START_DATE": "Select Start Date",
                "END_DATE": "Select completion Date",
                "JOB_DATE": "Job/Business Date",
                "ERROR_NETWORK": "Please check your Internet Connection",
                "SELECT_GENDER_SELECT": "Select Gender",
                "SELECT_GENDER_MALE": "Male",
                "SELECT_GENDER_FEMALE": "Female",
                "SELECT_GENDER_OTHERS": "Others",
                "SELECT_SCHOLARSHIP_SELECT": "Select Scholarship",
                "SELECT_SCHOLARSHIP_COST": "Cost",
                "SELECT_SCHOLARSHIP_OTHER": "Other",
                "SELECT_JOB_SELECT": "Select Job Status",
                "SELECT_JOB_TAKEN": "Taken",
                "SELECT_JOB_NOT_TAKEN": "Not Taken",
                "SELECT_FEEDBACK_SELECT": "Select Feedback",
                "SELECT_FEEDBACK_CENTERS": "Centers",
                "SELECT_FEEDBACK_COURSES": "Courses",
                "SELECT_FEEDBACK_SCHOLARSHIP": "Scholarship",
                "SELECT_FEEDBACK_JOBS": "Jobs",
                "SELECT_FEEDBACK_OTHER": "Other",
                "CENTER_SELECT_CITY": "Select City",
                "REGISTER_BUTTON_SUBMIT": "Submit",
                "MENU_IT_PARTNER": "IT Partner"
            },
          